### ISSUE TITLE
Tenacity version out of date

### ISSUE THREAD

**Issue by chrisgoddard** [jxnl/instructor#1000]
Hi there - the current tenacity version is out of date - it's currently pinned to the 8.* major version and 9.0.0 is now out - this is causing some compatibility issues with other libraries. 

If it would be possible to update this, it would be really helpful! Thanks!

**Comment by jxnl** [comment]
happy to accept pr on this

**Comment by ivanleomk** [comment]
Just merged a fix for this into the main branch, should be fixed in the next instructor release. Going to close this in preparation for this.
