### ISSUE TITLE
Add new parsing method to BatchJob

### ISSUE THREAD

**Issue by kwilsonmg** [jxnl/instructor#1031]
**Is your feature request related to a problem? Please describe.**
I would like to be able to not just parse from file in BatchJob but also parse from a string. This would be useful when you might programmatically download the result of the OpenAI batch job.

**Describe the solution you'd like**
A new method that works like BatchJob.parse_from_file but from a string. Example idea usage would be:

```python
client = instructor.from_openai(OpenAI())
file: Batch = client.client.batches.retrieve('batch_id')
filename = file.output_file_id
raw_content = client.client.files.content(filename)
content_text = raw_content.text
parsed, unparsed = BatchJob.parse_from_string(content=content_text, response_model=model)
```

**Describe alternatives you've considered**
The only alternative available would be to write the result to disk instead of keeping it in memory and passing that along, but that is clunky and involves unnecessary writes.

**Additional context**
I intend to work on the solution for this and will submit a pull request once I have it totally figured out and will update this description accordingly as well.

**Comment by ivanleomk** [comment]
This is available in instructor 1.5.2 so closing this issue
