### ISSUE TITLE
The multi classification does not actually work as intended. 

### ISSUE THREAD

**Issue by erickalfaro** [jxnl/instructor#104]
**Describe the bug**
The multi classification does not actually work as intended. 

**To Reproduce**
I copy paste the example for multi prediction and the outputs result in all the labels being predicted always. No matter the classes declared, the prompt used, the result is the same. All classes are predicted. 

examples/classification/multi_prediction.py

**Comment by jxnl** [comment]
i made some changes you're right they all pop up,
