### ISSUE TITLE
module 'instructor' has no attribute 'from_anthropic'

### ISSUE THREAD

**Issue by hyperbola-bear** [jxnl/instructor#1048]
- [x ] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x ] Other (claude-sonnet)

**Describe the bug**
it produces an error code saying module 'instructor' has no attribute 'from_anthropic', when the from_anthropic function clearly exist.

**To Reproduce**
use python3.10.10, pip install instructor anthropic, then run the code below
I'm using python3.10.10, instructor is 1.5.1, im running this Vscode jupyter notebook

**Expected behavior**
since the function exist i expect it to be able to call from_anthropic

**Screenshots**
trying to run this code to generate a x,y coordinate of a group of zones, given some coordinates
![image](https://github.com/user-attachments/assets/826c5c84-269e-47a7-8970-5812ec041d55)
```python
client = instructor.from_anthropic(Anthropic(api_key=""))

        zones = client.messages.create(
            model="claude-3-5-sonnet-20240620",
            max_tokens=1024,
            messages=[
                {
                    "role": "user",
                    "content": prompt.format(coords=coords, zones=accessed_zones),
                }
            ],
            response_model=SquashCourt,
        )

**Comment by ivanleomk** [comment]
Do you have the anthropic client installed?

**Comment by hyperbola-bear** [comment]
yeap i do
Name: anthropic
Version: 0.35.0
Summary: The official Python library for the anthropic API
Home-page:
Author:
Author-email: Anthropic <support@anthropic.com>
License:
Location: c:\users\clement\desktop\dawnflow\squashanalysisv3\.venv\lib\site-packages
Requires: anyio, distro, httpx, jiter, pydantic, sniffio, tokenizers, typing-extensions
Required-by:

**Comment by ivanleomk** [comment]
hmm a few questions - what version is your instructor and what version is anthropic. This should do the trick

```
pip list | grep -E "instructor|anthropic"
```

**Comment by ivanleomk** [comment]
Hmm I just tried reinstalling instructor and anthropic in a fresh virtual environment and I wasn't able to replicate this. Would it be possible to try reinstalling the library and anthropic in a fresh virtual environment?

```bash
venvivanleo@Ivans-MacBook-Pro test % uv venv venv
Using Python 3.11.9 interpreter at: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
Creating virtualenv at: venv
Activate with: source venv/bin/activate
ivanleo@Ivans-MacBook-Pro test % source venv/bin/activate
(venv) ivanleo@Ivans-MacBook-Pro test % uv pip install instructor anthropic
Resolved 43 packages in 300ms
Prepared 4 packages in 116ms
Installed 43 packages in 124ms
 + aiohappyeyeballs==2.4.3
 + aiohttp==3.10.9
 + aiosignal==1.3.1
 + annotated-types==0.7.0
 + anthropic==0.35.0
 + anyio==4.6.0
 + attrs==24.2.0
 + certifi==2024.8.30
 + charset-normalizer==3.3.2
 + click==8.1.7
 + distro==1.9.0
 + docstring-parser==0.16
 + filelock==3.16.1
 + frozenlist==1.4.1
 + fsspec==2024.9.0
 + h11==0.14.0
 + httpcore==1.0.6
 + httpx==0.27.2
 + huggingface-hub==0.25.1
 + idna==3.10
 + instructor==1.5.1
 + jiter==0.5.0
 + markdown-it-py==3.0.0
 + mdurl==0.1.2
 + multidict==6.1.0
 + openai==1.51.1
 + packaging==24.1
 + propcache==0.2.0
 + pydantic==2.9.2
 + pydantic-core==2.23.4
 + pygments==2.18.0
 + pyyaml==6.0.2
 + requests==2.32.3
 + rich==13.9.2
 + shellingham==1.5.4
 + sniffio==1.3.1
 + tenacity==8.5.0
 + tokenizers==0.20.0
 + tqdm==4.66.5
 + typer==0.12.5
 + typing-extensions==4.12.2
 + urllib3==2.2.3
 + yarl==1.14.0
(venv) ivanleo@Ivans-MacBook-Pro test % python3 ./test.py                  
chain_of_thought='To answer this question, let\'s consider the facts:\n\n1. The moon is not a country or a political entity, so it doesn\'t have a capital in the traditional sense.\n2. There are no permanent human settlements on the moon, let alone cities or administrative centers.\n3. The concept of a "capital" is typically associated with governing bodies on Earth.\n4. The moon is a natural satellite of Earth and is not divided into countries or regions with separate governments.\n\nGiven these facts, we can conclude that the moon does not have a capital.' answer="The moon does not have a capital. The concept of a capital city doesn't apply to the moon because it is not a country or political entity, and there are no permanent human settlements on its surface."
```

**Comment by hyperbola-bear** [comment]
somehow this did the trick, thanks

**Comment by ivanleomk** [comment]
Awesome, going to close this issue now

**Comment by edfenergy-yuhang** [comment]
Hi, I got the same attribute error:
AttributeError: module 'instructor' has no attribute 'from_anthropic'
my package version:
```
anthropic                                0.42.0
instructor                               1.7.2
```
I tried pip uninstall and install again but still not working.
