### ISSUE TITLE
Decoupling the llm backend

### ISSUE THREAD

**Issue by veeragoni** [jxnl/instructor#109]
**Is your feature request related to a problem? Please describe.**
I see the library is tightly coupled with openai function calling. but it would be good to decouple the model from pydantic way of doing things and use any model (llms from langchain) that way we can experiment with smaller/self-hosted/other cloud models

**Describe the solution you'd like**
ability to pass pydantic structures to any llm and get results back. for eample, something like using langchain tools where function calling is isolated from llm.

**Describe alternatives you've considered**
custom tools in langchain implementation for function calling

**Additional context**
not sure its already possible. I haven't experimented yet, but it looks like its coupled based on the repo subtitles /examples

**Comment by jxnl** [comment]
take a look at askmarvin.ai !

**Comment by jxnl** [comment]
what is the issue with using the pydantic output parser in langchain or llamaindex?
