### ISSUE TITLE
Default parameters to pydantic model

### ISSUE THREAD

**Issue by johngonzalez** [jxnl/instructor#115]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need send default parameters to pydantic response_model

**Describe the solution you'd like**
I want to send for example default _sex_ to model (don't extract data with ChatCompletion), because I know Jason's sex 😄 :

```python
class UserDetail(BaseModel, sex):
    weight: int
    sex: str
    def is_obese(self):
        if self.sex=='female' and self.weight>100:
            return True
        if self.sex=='male' and self.weight>120:
            return True
        return False


user: UserDetail = openai.ChatCompletion.create(
    model="gpt-3.5-turbo",
    response_model=UserDetail,
    parameters={'sex': 'male'}
    messages=[
        {"role": "user", "content": "Extract Jason 200kg"},
    ]
)
```

**Describe alternatives you've considered**
I'd considered create another pydantic class to complete properties for user. But it is not correct way, because UserDetail should have all user properties, some extracted from ChatCompletion and others send for me.

Maybe, I have lost something. I'm not expert using pydantic. If you can share me another option I would be grateful.

**Comment by jxnl** [comment]
i suggest taking a look at validation_context in the docs, might be good place to start
