### ISSUE TITLE
Clarify docs - is there a difference between calling a ChatCompletion with response_model parameter vs. using model.openai_schema and then using a function_call in the ChatCompletion?

### ISSUE THREAD

**Issue by ldorigo** [jxnl/instructor#127]
https://jxnl.github.io/instructor/#section-2-adding-additional-prompting Both options are shown, it's unclear if both can be used interchangeably? Or can OpenAISchema's only be used with function_call parameters of ChatCompletion s?

**Comment by jxnl** [comment]
one is a helper and wraps the other,.

with function_call, you have to parse the result yourself. with response_model you're always going to get a response of type `respone__model`

**Comment by ldorigo** [comment]
I see. Maybe it's there and I missed it, but might be good to write that in the docs, wasn't clear to me.
