### ISSUE TITLE
Doc  improvement: *why* would one use distillation?

### ISSUE THREAD

**Issue by ldorigo** [jxnl/instructor#128]
I was reading through the docs and saw https://jxnl.github.io/instructor/distillation/ . The page explains the "what" and the "how", but not the "why" - I assume this feature caters to some usecases, but it's not clear to me at all what those would be? The examples given seem like a ridiculously bad idea - replacing instantaneous, deterministic on-device calculations with slow, prone to hallucination api calls? Why would I ever want to use an LLM to perform simple math? I get they're just examples, but maybe it would be nice to have a paragraph explaining real usecases for this.

**Comment by ldorigo** [comment]
(btw: there's a mistake in the example:

```python
def fn(a: int, b: int) -> Multiply:
    # now this code will be short circuited and the model will be used instead.
    resp = a + b
    return Multiply(a=a, b=b, result=resp)
```

I assume you meant `resp = a*b`.)

**Comment by jxnl** [comment]
thats coming in the next blog! 

where we'll create a function call, do some additional work + validation, and then finetune a model where the original validation is now part of the output in a single step

**Comment by jxnl** [comment]
Check this out! https://jxnl.github.io/instructor/blog/2023/11/05/chain-of-density/
