### ISSUE TITLE
Upcoming openai-python 1.0.0 release

### ISSUE THREAD

**Issue by alexclaydon** [jxnl/instructor#130]
Hello.  Thanks for your great work on Instructor.  Really appreciate that it's thoughtfully constructed for use in production.

I wanted to check what your plans are for the upcoming openai-python 1.0.0 release (https://github.com/openai/openai-python/discussions/631).  Instructor currently has a dependency on <0.28.

Thanks!

**Comment by jxnl** [comment]
I'll just force 0.3.0 to be openai 1.0.0
and then see if people care about backwards compatibiltiy

**Comment by alexclaydon** [comment]
Thanks, sounds good to me.

**Comment by jxnl** [comment]
do you know when its going to roll out?

**Comment by alexclaydon** [comment]
Just launched as 1.1.0.

**Comment by jxnl** [comment]
oh god. time to migrate!

**Comment by alexclaydon** [comment]
Haha.  Fwiw, I just went through the process of vendoring some embeddings wrappers from LangChain to accommodate this openai-python 1.1.0 launch and it was mostly just a case of handling the new Pydantic response object: changing `["property"]` to `.property`, etc.

**Comment by jxnl** [comment]
i lied this is hard. 

mostly cause all my docs need to be rewritten, and the patching logic is different now.

**Comment by alexclaydon** [comment]
Makes sense.  Anyway, I guess we should all be happy that we finally have a stable 1.x client API to build on.

**Comment by jxnl** [comment]
https://github.com/jxnl/instructor/releases/tag/0.3.0rc

**Comment by marcoloco23** [comment]
Sounds like fun :) Great work so far! Currently using my own custom approach but will definitely look to switch when 1.0.0 is supported. Seems like a lot of the new functionalities (json support) should work really nicely with this.

**Comment by jxnl** [comment]
i wont support json mode, function calling has better mechanics on 'where to put the schema'

**Comment by DeoLeung** [comment]
need 3.0rc on pypi :)

**Comment by jxnl** [comment]
> need 3.0rc on pypi :)

not by my computer until tmr but if you're in need: 

```
git checkout grit/7a22fd10-39f8-484c-8730-0c48bfd9bd6d
pip install -e .
```

**Comment by alexclaydon** [comment]
Jason, do you think you'll  be adding support for function calling through the Assistants API?  Looks like `openai_function` and `OpenAISchema` might need a `from_tool_calls()` method - functionally similar to the current `from_response` methodsd - to handle the list of `RequiredActionFunctionToolCall` objects on `run.required_action.submit_tool_outputs.tool_calls`.
