### ISSUE TITLE
Example link 404

### ISSUE THREAD

**Issue by maxjeblick** [jxnl/instructor#140]
**Describe the bug**
Link to examples in README is currently broken.

**To Reproduce**
1. Click on "To see more examples of how we can create interesting models check out some [examples.](https://github.com/jxnl/instructor/blob/main/examples/index.md)" link in the README
2. Links to https://github.com/jxnl/instructor/blob/main/examples/index.md

**Expected behavior**
Links to https://jxnl.github.io/instructor/examples/

**Comment by jxnl** [comment]
min making a PR? otherwise I can take a look when i have time this week
should be a super small change from /docs

**Comment by maxjeblick** [comment]
Thanks for looking into this, I can create the PR.
