### ISSUE TITLE
Chain of density example broken

### ISSUE THREAD

**Issue by phiweger** [jxnl/instructor#166]
**Describe the bug**
The above mentioned example does not run, likely due to the API change from OpenAI

**To Reproduce**
1. Run the example
2. Fails with:

```python
     31 @staticmethod
     32 def extract_json(completion):
     33     for chunk in completion:
---> 34         if chunk["choices"]:
     35             delta = chunk["choices"][0]["delta"]
     36             if "function_call" in delta:

TypeError: 'ChatCompletionChunk' object is not subscriptable
```

The problem seems to be this line:

https://github.com/jxnl/instructor/blob/main/instructor/dsl/multitask.py#L34

Thanks for looking into this!

**Comment by phiweger** [comment]
Can confirm that this [PR](https://github.com/jxnl/instructor/blob/chain-of-density/examples/chain-of-density/chain_of_density.py) does the trick.

**Comment by jxnl** [comment]
away from computer right now, if you make a PR

1. fix
2. bump to 0.3.3

I can release asap

**Comment by jxnl** [comment]
its merged now!
