### ISSUE TITLE
Set up Pytest Coverage 

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#195]
This would be a huge lift! Simply do not know how and don't have much time right now...

Generally any improvements in test coverage would be great and having evals would be amazing

**Comment by cod3rck** [comment]
On it

**Comment by olumidedaramola21** [comment]
| Name                 | Stmts | Miss | Cover |
|----------------------|-------|------|-------|
| __init__.py          | 0     | 0    | 100%  |
| test_distil.py       | 56    | 8    | 86%   |
| test_function_calls.py| 34    | 1    | 97%   |
| test_multitask.py    | 9     | 0    | 100%  |
| test_patch.py        | 97    | 31   | 68%   |
| **TOTAL**            | 196   | 40   | 80%   |

**Comment by olumidedaramola21** [comment]
@jxnl did the table help?
