### ISSUE TITLE
Function description is too long?

### ISSUE THREAD

**Issue by ldorigo** [jxnl/instructor#214]
Hello, since this morning I am getting a lot of errors from the API like:

Error in getting response from model: Error code: 400 - {'error': {'message': '...' is too long - \'functions.0.description\'', 'type': 'invalid_request_error', 'param': None, 'code': None}}

Maybe OpenAI changed something ? I know that they now want you to use "tools" rather than "functions", so maybe it's to encourage people to do that instead?

**Comment by ivanleomk** [comment]
Hey Idorigo, do you happen to have a code sample you could show? Also, is this the first time you're running this api call against the API or has it been working well for some time but only just started throwing errors?
