### ISSUE TITLE
Support pydantic v1

### ISSUE THREAD

**Issue by talperetz** [jxnl/instructor#216]
Is your feature request related to a problem? Please describe.
I've encountered a limitation due to Instructor's current support exclusively for Pydantic v2. Many real-world, production-grade applications still predominantly use Pydantic v1. This version incompatibility restricts these applications from leveraging Instructor's functionality.

Describe the solution you'd like
I propose extending support to include Pydantic v1. This change would significantly widen Instructor's applicability, allowing a larger user base to benefit from its features. Ensuring compatibility with both versions of Pydantic would make Instructor more accessible and versatile.

Describe alternatives you've considered
Considered using langchain, or plain function calling.

Additional context
Many organizations are still operating on legacy systems that rely heavily on Pydantic v1. Providing support for this version would not only enhance the utility of Instructor but also showcase its adaptability to diverse user needs and environments.

**Comment by sudoskys** [comment]
Maybe you should standalone this service as a server and use a virtual environment
