### ISSUE TITLE
Support Multiple Modalies in Patch

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#217]
Recently, I believe the patch API should support multiple modes that modify the kwargs. Here's an example:

```python
from instructor import MODE

client = instructor.patch(OpenAI(), mode=MODE.FUNCTION_CALL)
client = instructor.patch(OpenAI(), mode=MODE.JSON_MODE)
client = instructor.patch(OpenAI(), mode=MODE.TOOL_CALL)
```

For JSON_MODE, we should:
1) Set `{"response_type": "json"}`.
2) Append a message that says "You must respond in the format {response_model.model_json_schema()}."

We can handle supporting tool call separately, but I think adding support for JSON mode might be beneficial for easier integration of local models.

**Comment by JoelKronander** [comment]
hmm, not sure I follow, but why not just handle that choice internally by default. 

ie depending on the capabilities of the model, use functions, json etc as needed under the hood?

Like some form of "auto" mode. maybe with specific settings to override, but that should probably be rare in practice?

**Comment by jxnl** [comment]
> hmm, not sure I follow, but why not just handle that choice internally by default.
> 
> ie depending on the capabilities of the model, use functions, json etc as needed under the hood?
> 
> Like some form of "auto" mode. maybe with specific settings to override, but that should probably be rare in practice?

"Explicit is better than implicit."
