### ISSUE TITLE
Missing Dependencies in Instructor Package: 'rich' and 'aiohttp' Not Automatically Installed

### ISSUE THREAD

**Issue by shanktt** [jxnl/instructor#231]
**Describe the bug**
The CLI tool fails due to missing 'rich' and 'aiohttp' dependencies. Running `instructor jobs --help` leads to `ModuleNotFoundError` for these modules, which are not automatically installed with the package.

**To Reproduce**

1. Install `instructor` in a new Python environment.
2. Run `instructor jobs --help `and observe `ModuleNotFoundError` for 'rich'.
3. Install 'rich', then rerun the command.
4. Observe `ModuleNotFoundError` for 'aiohttp'.
5. Install 'aiohttp', after which the command works.

**Expected behavior**
The package should include all necessary dependencies to prevent ModuleNotFoundError.

**Comment by ivanleomk** [comment]
Thanks for highlighting this. Let me push up a PR for this.

**Comment by ivanleomk** [comment]
@AshankKumar , this should be fixed once we publish a new release. The change is already in the library :)
