### ISSUE TITLE
Examples and Docs on using GPT-vision Models with structured extraction, 

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#235]
using images to extradt structured data would be cool, i bet it works well with json mode

**Comment by shanktt** [comment]
Is json mode supported by `gpt-4-vision-preview`?. The docs only mention [support](https://platform.openai.com/docs/guides/text-generation/json-mode) for `gpt-4-1106-preview ` and `gpt-3.5-turbo-1106`. Though an example chaining a call from `gpt-4-vision-preview` to a model that supports structured output like json mode or function calling would be helpful to people

**Comment by waseemhnyc** [comment]
Hey @jxnl. I think this would be a great idea. 
I started working on this repo: [Object Detection using OpenAI GPT4-V](https://github.com/waseemhnyc/object-detection-openai.git)

In the main.py file you can see the long system instructions and where I am doing string manipulating and casting to JSON:
```python
content = response.choices[0].message.content
json_str = content.strip('`json\n') # Extract the JSON part from the string (remove the ```json and ``` at both ends)
coordinates = json.loads(json_str) # Convert the JSON string into a Python dictionary
```
**I've been getting good results...** 
but lets say you try to ask a question like "Detect balloons" and there are no balloons in an image - you get an error trying to grab the data. 
The response can be predictable, if the prompt is predictable.

This is where instructor would be awesome. You could have default values, cleaner prompt messages in the docstring and field annotations etc etc.

Tried a basic example with instructor [here](https://github.com/waseemhnyc/object-detection-openai/blob/main/main_instructor.py). But as @shanktt said `gpt-4-vision-preview` does not support `functions` and `response_format`. 

```bash
  File "/Users/waseemh/Projects/image-detection-openai/venv/lib/python3.11/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/waseemh/Projects/image-detection-openai/venv/lib/python3.11/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': '2 validation errors for Request\nbody -> function_call\n  extra fields not permitted (type=value_error.extra)\nbody -> functions\n  extra fields not permitted (type=value_error.extra)', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

I assume `gpt-4-vision-preview` will allow `functions` and `response_format` in the near future - but do you have any thoughts on how we can have it supported in the mean time. 
Maybe this "patch" could be helpful for other future features OpenAI releases.

**Comment by jxnl** [comment]
Looks like need to support something else like code block mode.

**Comment by waseemhnyc** [comment]
Beat me to it @Anmol6. Looking forward to this fix.

**Comment by guilhemchalancon** [comment]
> Is json mode supported by `gpt-4-vision-preview`?. The docs only mention [support](https://platform.openai.com/docs/guides/text-generation/json-mode) for `gpt-4-1106-preview ` and `gpt-3.5-turbo-1106`. Though an example chaining a call from `gpt-4-vision-preview` to a model that supports structured output like json mode or function calling would be helpful to people

Unfortunately not a planned feature as of yet: https://github.com/openai/openai-node/issues/469#issuecomment-1804985848

**Comment by Anmol6** [comment]
@jxnl can we close?
