### ISSUE TITLE
Improve Contributions page for documentation

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#239]
0. explain mkdocs serve 
1. explain hl_lines: https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
2. explain admonitions: https://squidfunk.github.io/mkdocs-material/reference/admonitions/?h=admon#usage

Just a few short blurbs and links would be enough

all root docs are here https://squidfunk.github.io/mkdocs-material/

**Comment by tadash10** [comment]
hi there ! I just updated the contributing file . Let me know if you prefer any modifications
