### ISSUE TITLE
Instructor's `response_model` doesn't typecheck

### ISSUE THREAD

**Issue by gkossakowski** [jxnl/instructor#260]
**Describe the bug**
Instructor's patch of openai's `completions.create` doesn't typecheck when used with `response_model`.

**To Reproduce**
Use the sample code from the README and open a project in VSCode with pylance installed.

**Expected behavior**
The code type-checks.

**Screenshots**
<img width="1198" alt="image" src="https://github.com/jxnl/instructor/assets/4217/e0772bb3-ef4f-4781-bbd1-bc771bdbdec8">

**Comment by gkossakowski** [comment]
I don't think the culprit is with the inference of the type of `user` variable. The problem is with the type of `create` method not having `response_model` as the argument.

**Comment by jxnl** [comment]
ah got it, yeah i do a patch instead of subclassing the entire client, do you have any suggestions? I should probs spend some time on this when i have time.

**Comment by gkossakowski** [comment]
I'm not an expert on Python typing but I'd start fixing this issue:

<img width="871" alt="image" src="https://github.com/jxnl/instructor/assets/4217/e74a5f8e-458e-4bec-89a5-82fb53a99b93">

You see that the inferred type from `patch` is a union of sync and async client. You don't want a union but you want the type to be dependent on `streaming` argument which determines which of the two variants in the union should be picked.

For expressing the extension of `create` method, I asked ChatGPT: https://chat.openai.com/share/6a69c8e7-29de-4b56-9ce2-211dc046fa5c

Based on my type-checking experience from my previous life, ChatGPT's idea check out at first look.

**Comment by gkossakowski** [comment]
By the way, are you not using type-checking yourself?

**Comment by jxnl** [comment]
i dont use the strictest mode, this is super helpful I'll see if someone can help out with this

**Comment by gao-hongnan** [comment]
> i dont use the strictest mode, this is super helpful I'll see if someone can help out with this

_Not an expert_ in **[typing theory](https://peps.python.org/pep-0483/)** as well (need to revise on concepts such as `covariant`, `contravariant`). But I do _attempt_ to adopt _slightly strict_ static type checks in python based projects.

I take reference of the strictness from [OpenAI](https://github.com/openai/openai-python/blob/main/mypy.ini), and [PyTorch](https://github.com/pytorch/pytorch/blob/main/mypy-strict.ini) and use `mypy` as the static type checker.

I can raise a PR to implement **pre-commit hooks** (or `make`/scripts) for local static type checking, and **continuous-integration** checks in the containerized environment in GitHub Actions (both local and github actions should refer to the same set of `mypy` configurations unless there's a strong reason to deviate).

---

```bash
$ mypy --no-pretty \
     --color-output \
     --strict \
     --python-version=3.9 \
     --config-file=.mypy.ini \
     instructor/patch.py
```

Following is a sample snippet of the result of using `mypy` on `strict` mode (command above):

```txt
instructor/patch.py:53: error: Unsupported left operand type for + ("None")  [operator]
instructor/patch.py:53: error: No overload variant of "__add__" of "list" matches argument type "str"  [operator]
instructor/patch.py:53: note: Possible overload variants:
instructor/patch.py:53: note:     def __add__(self, list[Union[ChatCompletionContentPartTextParam, ChatCompletionContentPartImageParam]], /) -> list[Union[ChatCompletionContentPartTextParam, ChatCompletionContentPartImageParam]]
instructor/patch.py:53: note:     def [_S] __add__(self, list[_S], /) -> list[Union[_S, ChatCompletionContentPartTextParam, ChatCompletionContentPartImageParam]]
instructor/patch.py:53: note: Left operand is of type "Union[str, None, list[Union[ChatCompletionContentPartTextParam, ChatCompletionContentPartImageParam]]]"
```

**Comment by barapa** [comment]
For the sync client, I have written a simple wrapper class around the patched client that allows the rest of my code to avoid type issues.

```python
from typing import TypeVar, Generic, Type
import instructor

from openai import OpenAI

# Define a generic type for the response model
T = TypeVar("T")


class StructuredOpenAI(Generic[T]):
    """A wrapper class around instructor's patched OpenAI client.

    This simple wrapper allows us to avoid type errors when using Instructor's patched OpenAI client.

    """

    def __init__(self, openai_client: OpenAI):
        self._client = instructor.patch(openai_client)

    def create(
        self,
        response_model: Type[T],
        max_retries: int = 1,
        validation_context=None,
        *args,
        **kwargs,
    ) -> T:
        return self._client.chat.completions.create(  # type: ignore
            response_model=response_model,
            validation_context=validation_context,
            max_retries=max_retries,
            *args,
            **kwargs,
        )

```

**Comment by gkossakowski** [comment]
How do you use this class? Doesn't it make sense to patch the upstream, i.e. instructor itself with similar code structure?

**Comment by jxnl** [comment]
i don't hate it.

**Comment by savarin** [comment]
Hi everyone! I'm new and thought it would be interesting to contribute by adding types (I've only had one open source contribution and it's adding types to [urllib3](https://github.com/urllib3/urllib3/issues/1897)).

Reviewing the dependency graph I thought it would make sense to start with `instructor.exceptions` and `instructor.function_calls`.

![image](https://github.com/jxnl/instructor/assets/5699412/dc44c083-f272-445a-928e-721821e0738c)

The remaining errors I'm seeing relate to `BaseModel` having type `Any` and `function_calls.OpenAISchema.openai_schema` being both a property and a class method.

```
> mypy --python-version=3.9 --color-output --no-pretty --follow-imports=skip instructor/cli/cli.py instructor/cli/usage.py instructor/exceptions.py instructor/function_calls.py
instructor/function_calls.py:36: error: Class cannot subclass "BaseModel" (has type "Any")  [misc]
instructor/function_calls.py:77: error: Only instance methods can be decorated with @property  [misc]
instructor/function_calls.py:158: error: Value of type "Callable[[], dict[str, Any]]" is not indexable  [index]
instructor/function_calls.py:171: error: Value of type "Callable[[], dict[str, Any]]" is not indexable  [index]
instructor/function_calls.py:223: error: Value of type "Callable[[], dict[str, Any]]" is not indexable  [index]
instructor/function_calls.py:236: error: Value of type "Callable[[], dict[str, Any]]" is not indexable  [index]
```

I have a draft PR [here](https://github.com/jxnl/instructor/pull/374) that I'm still working on, just wondering more broadly if these changes are helpful and if not, is there another area that makes more sense to add types to? Do we even want to add types? Thanks!

**Comment by gkossakowski** [comment]
If your changes would make the original error I reported go away, it would be hugely helpful.

**Comment by savarin** [comment]
Ach so https://github.com/jxnl/instructor/pull/372

**Comment by jxnl** [comment]
@savarin happy to take contribs into `types`

**Comment by quickpanda** [comment]
> Reviewing the dependency graph I thought it would make sense to start with `instructor.exceptions` and `instructor.function_calls`.

Hi, just saw this thread. While this might be slightly tangential to the main issue, I'm interested in how you created this dependency graph. Could you share the method or tools you used for this? 
@savarin

**Comment by savarin** [comment]
@quickpanda Sure I used pydeps (`pip install pydeps`, then `pydeps instructor`).

**Comment by savarin** [comment]
New types umbrella issue here https://github.com/jxnl/instructor/issues/390

**Comment by savarin** [comment]
@gkossakowski Can I check what you're seeing now (I use Sublime 😅)? We've extended type coverage so now the following passes.

```
mypy --python-version=3.9 --color-output --no-pretty --follow-imports=skip instructor/run.py
```
