### ISSUE TITLE
Validation errors while streaming objects

### ISSUE THREAD

**Issue by wantpinow** [jxnl/instructor#269]
**Is your feature request related to a problem? Please describe.**
When iterating over a generator that yields results validated by a Pydantic model, a `ValidationError` within the generator halts further iteration even when some items in the stream are valid. For example, if one element does not meet the model's requirements, the entire iteration stops instead of skipping the invalid entry and continuing with the rest.

**Describe the solution you'd like**
Errors in validations for single iterations of a generator should (optionally) be quietly ignored, rather than breaking the whole generation. See the snippet below for an example:

```
import instructor  # noqa
from openai import OpenAI  # noqa
from typing import Iterable  # noqa
import json  # noqa
from dotenv import load_dotenv  # noqa
from pydantic import BaseModel, validator, ValidationError  # noqa

load_dotenv()

client = instructor.patch(OpenAI())

class Person(BaseModel):
    name: str

    @validator("name")
    def name_cannot_be_alice(cls, value):
        if value.lower() == "bob":
            raise ValueError('name cannot be "bob"')
        return value


messages = [
    {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
    {
        "role": "user",
        "content": "Return a list of 3 JSON objects. The first object must have a key 'name' with the value 'alice'. The second object must have a key 'name' with the value 'bob'. The third object must have a key 'name' with the value 'carol'.",
    },
]

stream = client.chat.completions.create(
    model="gpt-3.5-turbo-1106",
    temperature=0,
    seed=42,
    response_model=Iterable[Person],
    messages=messages,
    stream=True,
    max_tokens=1000,
)

for item in stream:
    print(item)
```

**Proposed solution**
Wrap line 35 in `instructor/dsl/multitask.py` in a try-except block:

```
            if task_json:
                try:
                    obj = cls.task_type.parse_raw(task_json)  # type: ignore
                    yield obj
                except ValidationError as e:
                    continue
```

I made this change locally and it seems to work for the example above.

I don't know whether you'd want this behaviour to be opt-in via an additional flag or not, but I would appreciate the feature nonetheless as I don't think there's a workaround for catching exceptions raised by a generator internally.

**Comment by jxnl** [comment]
would actually love a contribution, if you wrap it i'll try to think about the right way to set that flag 

something like 

`throw_stream_exceptions` or something.

**Comment by wantpinow** [comment]
yeah exactly, i'll start a PR 👍 thanks for the repo btw, super neat and saves me from langchain nightmares 😅

**Comment by wantpinow** [comment]
I gave it a stab and added a `throw_stream_exceptions `: see this PR #270 (https://github.com/jxnl/instructor/pull/270).

Let me know what you think 👍
