### ISSUE TITLE
Detect finish_reason "length" vs "stop" and throw error

### ISSUE THREAD

**Issue by ionflow** [jxnl/instructor#276]
**Is your feature request related to a problem? Please describe.**
If the max_tokens length is too short for the output it doesn't seem like we get any valuable indication that the finish reason was due to length and not the LLM stopping token generation. For example the output of this particular request needs about 200 tokens.
```
response = client.chat.completions.create(
    model=settings.GPT_3_5,
    messages=messages,
    max_tokens=100,
    temperature=0,
    response_model=ResponseModel,
    response_format={"type": "json_object"},
)
```
The error I get is:
```
1 validation error for ResponseModel
  Invalid JSON: EOF while parsing a string at line 1 column 391 [type=json_invalid, input_value='{"query":"family photos ...Getty Images"},{"url":"', input_type=str]
```

**Describe the solution you'd like**
I can parse this error and look for "JSON: EOF" or the lack of an ending "}" or something like that, but it would be nice to have a more explicit indication that the reason was the `finish_reason == "length"`. Otherwise we're just guessing this is the problem.

**Describe alternatives you've considered**
Could possibly even include a `max_allowed_tokens` property that gets used in any retries where this error is due to `finish_reason` of "length".

**Additional context**
We don't always know how long the output is going to be even when defining the model in detail using Pydantic.

**Comment by jxnl** [comment]
interesting, i thin kwe can update `from_response` to check for finish reason and throw a different error, would happily accept a PR! Otherwise i'll make this as a good first ticket

**Comment by ionflow** [comment]
I have a PR if you're interested. 😄
