### ISSUE TITLE
Add debugging option for model response

### ISSUE THREAD

**Issue by alew3** [jxnl/instructor#280]
When testing new models. It would be nice to have an option to view what is being returned by the model before being validated so it can be debugged.

**Comment by jxnl** [comment]
how would you like that api to work?

I could just add a logger.debug and allow you to control via levels?

**Comment by alew3** [comment]
Yes, that would work!

**Comment by jxnl** [comment]
shows something simple like this https://github.com/jxnl/instructor/pull/283

**Comment by alew3** [comment]
Tried it out and is exactly what I was looking for.
