### ISSUE TITLE
Compatibility with open models

### ISSUE THREAD

**Issue by tnunamak** [jxnl/instructor#282]
With open models becoming more capable at providing structured output, it would be great if there was a way to use them with Instructor.

Maybe this is already possible by using an OpenAI-compatible API to host an open model--if so, can anyone who has gotten this working share their workflow?

**Comment by jxnl** [comment]
theres some notes here: https://jxnl.github.io/instructor/examples/open_source/

**Comment by jxnl** [comment]
anyscale mistral supports `mode=Mode.JSON_SCHEMA` as well!

**Comment by tnunamak** [comment]
I overlooked that, thank you!

**Comment by jxnl** [comment]
no problem our docs need work, if you ever want to contribute I'd love to get some support cleaning that up!
