### ISSUE TITLE
Trying to use Mixtral @ Anyscale but it doesn't return a clean JSON after a retry and fails

### ISSUE THREAD

**Issue by alew3** [jxnl/instructor#286]
My code is working to extract data from a PDF with ChatGPT4 turbo, but when I try to change it to mistralai/Mixtral-8x7B-Instruct-v0.1 model from AnyScale It always includes text apologizing on the retry and messes up the JSON for processing.  I've tried changing the prompt telling it to only return JSON, but no luck so far.

Error response: ChatCompletion(id='mistralai/Mixtral-8x7B-Instruct', choices=[Choice(finish_reason='stop', index=0, message=ChatCompletionMessage(content=' I apologize for the error in my previous response. It appears that there was some extra text included in my response that caused the JSON to be invalid. Here is the corrected JSON response:

**Comment by alew3** [comment]
Relevant code:

client = instructor.apatch(AsyncOpenAI(api_key=settings.LLM_API_KEY,base_url=settings.LLM_URL), mode=Mode.JSON)


resume = await client.chat.completions.create(
            model=settings.LLM_MODEL,
            response_model=Model,
            response_format = { 
                type: "json_object" 
            },
            max_retries=1,
            messages=[
                {
                    "role": "user",
                    "content": instructions,
                }
            ],
        )

**Comment by alew3** [comment]
the response includes ```json  markdown formatted with the correct response but because it starts with 'Based on the instructions provided,' if fails.   If the json could be extracted before processing the model it would bypass this issue.

**Comment by jxnl** [comment]
Mode.JSON_SCHEMA 

Works better

**Comment by jxnl** [comment]
https://jxnl.github.io/instructor/blog/2023/12/15/patching/

**Comment by alew3** [comment]
Thanks for the link. But not having much luck, whatever mode I set with Anyscale I get back an invalid json as there are comments being made in the response from the model. Tried JSON, JSON_SCHEMA modes and all kinds of prompts so that there wouldnt be comments from the model.

**Comment by alew3** [comment]
My model is quite complex, that might be triggering the comments. But the same code works fine with ChatGPT-4

**Comment by alew3** [comment]
I guess it is a model limitation as per ANYSCALE reference: https://docs.endpoints.anyscale.com/supported-models/mistralai-Mixtral-8x7B-Instruct-v0.1
