### ISSUE TITLE
Deprecate Mode.FUNCTIONS

### ISSUE THREAD

**Issue by Phodaie** [jxnl/instructor#294]
**Describe the change**
Since function calling has be deprecated in the latest OpenAI APIs, it makes sense to also deprecate .FUNCTIONS Mode in Instructor. This will reduce confusion for the new users of the library.

As a minumum Modę.TOOLS should be the default for handle_response_model, process_response, retry_async, wrap_chatcompletion, patch, and apatch functions.

**Comment by jxnl** [comment]
Agreed. Can you make a PR and bump to 0.5.0?
