### ISSUE TITLE
support for NexusRaven-V2 function call

### ISSUE THREAD

**Issue by lan2720** [jxnl/instructor#302]
NexusRaven-V2 surpasses GPT4 in function calling benchmarks, and is more versatile than the OpenAI Function Calling API. It provides python sdk for usage. I wonder how i can use it in instructor? Thank you!

- https://pypi.org/project/nexusraven/
- https://huggingface.co/Nexusflow/NexusRaven-V2-13B

**Comment by joshpopelka20** [comment]
What was the fix for this? I'm trying to use a fine-tuned Llama3 model from HuggingFace [https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B](https://huggingface.co/NousResearch/Hermes-2-Pro-Llama-3-8B)
