### ISSUE TITLE
`Maybe` should use outer `MaybeBase` for better type checking

### ISSUE THREAD

**Issue by dalberto** [jxnl/instructor#307]
**Describe the bug**
Currently, `Maybe` builds a model based on the locally-defined `MaybeBase`:

https://github.com/jxnl/instructor/blob/8ac5518b1098363ccc0dc77bfdc89be2c0d3a0db/instructor/dsl/maybe.py#L77

This works as expected, but it means any type hints that constrain objects to the outer `MaybeBase` fail because the Maybe model class has the locally-defined `MaybeBase` as its base.

**To Reproduce**
```python
from typing import Optional

from instructor import Maybe
from instructor.dsl.maybe import MaybeBase
from pydantic import BaseModel, Field


class UserDetail(BaseModel):
    age: int
    name: str
    role: Optional[str] = Field(default=None)


MaybeUserDetail = Maybe(UserDetail)

issubclass(MaybeUserDetail, MaybeBase)  # False
 ```

**Expected behavior**
```python
issubclass(MaybeUserDetail, MaybeBase)  # True
```
**Screenshots**
N/A

**Comment by jxnl** [comment]
ah thanks for catching this, i'd take a PR for this to fix, i figured most people would just implement it themselves

**Comment by dalberto** [comment]
Addressed in https://github.com/jxnl/instructor/pull/325, let me know what you think!
