### ISSUE TITLE
Any examples on how to use the library without having to use the .patch method?

### ISSUE THREAD

**Issue by Mistobaan** [jxnl/instructor#314]
I really like the premises of the library, found it through this [blog post](https://wandb.ai/jxnlco/function-calls/reports/Better-Data-Extraction-Using-Pydantic-and-OpenAI-Function-Calls--Vmlldzo0ODU4OTA3).

I don't like the .patch method. at all. it doesn't work for other clients that are not the openai ones.
I liked the clean example of being able to do something like this:

```python
@instructor.register('function-group')
class Search(instructor.FunctionCall):
       arg1: Field ..
       arg2: Field ... 

client.chat.completion({
#...
tools=instructor.list_definitions('function-group')
})
```

any technical reasons why you went the `.patch` way? Is the original form still supported? any examples?
Thanks

**Comment by jxnl** [comment]
patch is the minimally invasive option imo.

if you wante a group i'd do: https://jxnl.github.io/instructor/concepts/union/

**Comment by pawel-krzych** [comment]
@Mistobaan you can call OpenAI API endpoint directly and set `functions` and `function_call` in this way:

```
from instructor.function_calls import OpenAISchema, openai_schema

if not issubclass(response_model, OpenAISchema):
    response_model = openai_schema(response_model)
payload["functions"] = [response_model.openai_schema]
payload["function_call"] = {"name": response_model.openai_schema["name"]}
```

`response_model` is a class inheriting the BaseModel from Pydantic.
