### ISSUE TITLE
enable max_retries with tool choice calls

### ISSUE THREAD

**Issue by marcasty** [jxnl/instructor#322]
**Is your feature request related to a problem? Please describe.**
I've found tool mode to be more effective than json mode, but I like the max_retries functionality in json mode and it's not enabled for tool mode.

**Describe the solution you'd like**
in retry_sync()/retry_async() patch.py, after L242/L288 
https://github.com/jxnl/instructor/blob/9f8714b5f09c832206ea8fdbff271f58ec99351b/instructor/patch.py#L288

append a dict to the messages list 

kwargs["messages"].append({
"tool_call_id": "<ID from tool call assistant message",
"role": "tool",
"name": "<function name>",
"content": "Failure"
})
*NOTE: I believe content can be any string

**Describe alternatives you've considered**
I could implement the feedback loop in my own code by encasing the instructor tool choice call in a try/except statement, but it would be cleaner if this feedback is under the hood like it is in other modes 

**Additional context**
OpenAI makes you respond to an assistant tool choice with the tool_call_id stuff but it's trivial to implement, I actually do this when I write fewshot tool_choice examples. I just think it would be nice to implement this in instructor to handle max retries and shorten the feedback loop when the structured LLM response fails. 

If there's interest, I'll submit a PR today

**Comment by jxnl** [comment]
Lets do it! just attach me to the PR review and update tests :)

**Comment by marcasty** [comment]
@jxnl [https://github.com/jxnl/instructor/pull/323](url) I think this gets the job done
