### ISSUE TITLE
when i run the auto_dataframe.py sample get the error like this

### ISSUE THREAD

**Issue by cumthxy** [jxnl/instructor#324]
Traceback (most recent call last):
  File "/Users/huangxingyu/daily/chatgpt/1.py", line 65, in <module>
    df = dataframe(
  File "/Users/huangxingyu/daily/chatgpt/1.py", line 61, in dataframe
    return Dataframe.from_response(completion)
  File "/Users/huangxingyu/anaconda3/envs/python3.9/lib/python3.9/site-packages/instructor/function_calls.py", line 138, in from_response
    return cls.model_validate_json(
  File "/Users/huangxingyu/anaconda3/envs/python3.9/lib/python3.9/site-packages/pydantic/main.py", line 532, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for Dataframe
data.0
  Input should be an object [type=model_type, input_value=['John', 25, 'New York', 'basketball'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
data.1
  Input should be an object [type=model_type, input_value=['Mike', 30, 'San Francisco', 'baseball'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
data.2
  Input should be an object [type=model_type, input_value=['Sarah', 20, 'Los Angeles', 'tennis'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type
data.3
  Input should be an object [type=model_type, input_value=['Mary', 35, 'Chicago', None], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/model_type

**Comment by jxnl** [comment]
share prompt, i can't do anything with this.

**Comment by cumthxy** [comment]
> share prompt, i can't do anything with this.
 use this code  this is the example in your project 

https://github.com/jxnl/instructor/blob/main/examples/automatic_dataframe_extraction/auto_dataframe.py

import instructor
from instructor import OpenAISchema
from pydantic import Field
from typing import List, Any
from openai import OpenAI

client = OpenAI()


class RowData(OpenAISchema):
    row: List[Any] = Field(..., description="The values for each row")


class Dataframe(OpenAISchema):
    """
    Class representing a dataframe. This class is used to convert
    data into a frame that can be used by pandas.
    """

    data: List[RowData] = Field(
        ...,
        description="Correct rows of data aligned to column names, Nones are allowed",
    )
    columns: List[str] = Field(
        ...,
        description="Column names relevant from source data, should be in snake_case",
    )

    def to_pandas(self):
        import pandas as pd

        columns = self.columns
        data = [row.row for row in self.data]

        return pd.DataFrame(data=data, columns=columns)


def dataframe(data: str) -> Dataframe:
    print("Dataframe.openai_schema",Dataframe.openai_schema)
    completion = client.chat.completions.create(
        model="gpt-3.5-turbo-0613",
        temperature=0.1,
        functions=[Dataframe.openai_schema],
        function_call={"name": Dataframe.openai_schema["name"]},
        messages=[
            {
                "role": "system",
                "content": """Map this data into a dataframe a
            nd correctly define the correct columns and rows""",
            },
            {
                "role": "user",
                "content": f"{data}",
            },
        ],
        max_tokens=1000,
    )
    return Dataframe.from_response(completion)


if __name__ == "__main__":
    df = dataframe(
        """My name is John and I am 25 years old. I live in 
        New York and I like to play basketball. His name is 
        Mike and he is 30 years old. He lives in San Francisco 
        and he likes to play baseball. Sarah is 20 years old 
        and she lives in Los Angeles. She likes to play tennis.
        Her name is Mary and she is 35 years old. 
        She lives in Chicago."""
    )

    print(df.to_pandas())
    """
        name  age       location       hobby
    0   John   25       New York  basketball
    1   Mike   30  San Francisco    baseball
    2  Sarah   20    Los Angeles      tennis
    3   Mary   35        Chicago        None
    """

**Comment by cumthxy** [comment]
> share prompt, i can't do anything with this.

this code  https://github.com/jxnl/instructor/blob/main/examples/automatic_dataframe_extraction/auto_dataframe.py

**Comment by jxnl** [comment]
try using this instead, https://github.com/jxnl/instructor/blob/main/examples/vision/run_table.py ! I'lll delete this example and replace it with markdown

**Comment by jxnl** [comment]
```python
from openai import OpenAI
from io import StringIO
from typing import Annotated, Any, Iterable
from openai import OpenAI
from pydantic import (
    BaseModel,
    BeforeValidator,
    PlainSerializer,
    InstanceOf,
    WithJsonSchema,
)
import pandas as pd
from tomlkit import table
import instructor


client = instructor.patch(OpenAI(), mode=instructor.function_calls.Mode.MD_JSON)


def md_to_df(data: Any) -> Any:
    if isinstance(data, str):
        return (
            pd.read_csv(
                StringIO(data),  # Get rid of whitespaces
                sep="|",
                index_col=1,
            )
            .dropna(axis=1, how="all")
            .iloc[1:]
            .map(lambda x: x.strip())
        )
    return data


MarkdownDataFrame = Annotated[
    InstanceOf[pd.DataFrame],
    BeforeValidator(md_to_df),
    PlainSerializer(lambda x: x.to_markdown()),
    WithJsonSchema(
        {
            "type": "string",
            "description": """
                The markdown representation of the table, 
                each one should be tidy, do not try to join tables
                that should be seperate""",
        }
    ),
]


class Table(BaseModel):
    caption: str
    dataframe: MarkdownDataFrame


client = instructor.patch(OpenAI())


tables = client.chat.completions.create(
    model="gpt-3.5-turbo",
    response_model=Iterable[Table],
    messages=[
        {
            "role": "system",
            "content": "Please extract the tables from the following text, merge as much as possible:",
        },
        {
            "role": "user",
            "content": """
        My name is John and I am 25 years old. I live in 
        New York and I like to play basketball. His name is 
        Mike and he is 30 years old. He lives in San Francisco 
        and he likes to play baseball. Sarah is 20 years old 
        and she lives in Los Angeles. She likes to play tennis.
        Her name is Mary and she is 35 years old. 
        She lives in Chicago.
        """,
        },
    ],
)

for table in tables:
    print(table.caption)
    print(table.dataframe)
    print()
    """
    People
            Age           City       Hobby 
    Name                                   
    John      25       New York  Basketball
    Mike      30  San Francisco    Baseball
    Sarah     20    Los Angeles      Tennis
    Mary      35        Chicago         N/A
    """
```


thanks for finding the regression, going to delete the example to use this one isntead.

**Comment by cumthxy** [comment]
> ```python
> from openai import OpenAI
> from io import StringIO
> from typing import Annotated, Any, Iterable
> from openai import OpenAI
> from pydantic import (
>     BaseModel,
>     BeforeValidator,
>     PlainSerializer,
>     InstanceOf,
>     WithJsonSchema,
> )
> import pandas as pd
> from tomlkit import table
> import instructor
> 
> 
> client = instructor.patch(OpenAI(), mode=instructor.function_calls.Mode.MD_JSON)
> 
> 
> def md_to_df(data: Any) -> Any:
>     if isinstance(data, str):
>         return (
>             pd.read_csv(
>                 StringIO(data),  # Get rid of whitespaces
>                 sep="|",
>                 index_col=1,
>             )
>             .dropna(axis=1, how="all")
>             .iloc[1:]
>             .map(lambda x: x.strip())
>         )
>     return data
> 
> 
> MarkdownDataFrame = Annotated[
>     InstanceOf[pd.DataFrame],
>     BeforeValidator(md_to_df),
>     PlainSerializer(lambda x: x.to_markdown()),
>     WithJsonSchema(
>         {
>             "type": "string",
>             "description": """
>                 The markdown representation of the table, 
>                 each one should be tidy, do not try to join tables
>                 that should be seperate""",
>         }
>     ),
> ]
> 
> 
> class Table(BaseModel):
>     caption: str
>     dataframe: MarkdownDataFrame
> 
> 
> client = instructor.patch(OpenAI())
> 
> 
> tables = client.chat.completions.create(
>     model="gpt-3.5-turbo",
>     response_model=Iterable[Table],
>     messages=[
>         {
>             "role": "system",
>             "content": "Please extract the tables from the following text, merge as much as possible:",
>         },
>         {
>             "role": "user",
>             "content": """
>         My name is John and I am 25 years old. I live in 
>         New York and I like to play basketball. His name is 
>         Mike and he is 30 years old. He lives in San Francisco 
>         and he likes to play baseball. Sarah is 20 years old 
>         and she lives in Los Angeles. She likes to play tennis.
>         Her name is Mary and she is 35 years old. 
>         She lives in Chicago.
>         """,
>         },
>     ],
> )
> 
> for table in tables:
>     print(table.caption)
>     print(table.dataframe)
>     print()
>     """
>     People
>             Age           City       Hobby 
>     Name                                   
>     John      25       New York  Basketball
>     Mike      30  San Francisco    Baseball
>     Sarah     20    Los Angeles      Tennis
>     Mary      35        Chicago         N/A
>     """
> ```
> 
> thanks for finding the regression, going to delete the example to use this one isntead.

why i get error in the old code?

**Comment by jxnl** [comment]
probably the llm changed
