### ISSUE TITLE
Azure OpenAI compatibility with Instructor

### ISSUE THREAD

**Issue by TempoShaman** [jxnl/instructor#338]
**Describe the bug**
When trying to use Pydantic validation class with Instructor's response_model, Azure OpenAI throws error saying that both Functions and Tools cannot be used together. I've noticed there was some push for refactoring the "function_calls.py". I've done the changes locally but it still fails.

**These are versions I am currently using:**
GPT_MODEL = "gpt-35-turbo-16k"
api_version="2023-12-01-preview"
openai version= 1.7.1
I've tried openai version 1.5.0, but it's the same.

**Code example:**

This is my validator class:

```
class SQLValidator(BaseModel):
    question: str
    answer: Annotated[
        str,
        BeforeValidator(
            instructor.llm_validator("SQL query must be logically and syntactically correct.", allow_override=True)
        )
    ]

```
and it is used here:

```
response = self.client.chat.completions.create(
                model=self.GPT_MODEL,
                messages=st.session_state.conversation_history,
                tools=tools,
                tool_choice="auto",
                temperature=0,
                response_model = SQLValidator,
                max_retries=2
            )
```

This is the error:
<img width="326" alt="image" src="https://github.com/jxnl/instructor/assets/80389825/2814f2a5-0086-4b37-82d7-e75265cbbcf8">

Am I doing some silly mistake or is this problem with compatibility of Azure OpenAI service with Instructor?

**Edit:** 
I have verified that the same error goes for Non-Azure version of OpenAI as well.

**Comment by jxnl** [comment]
you cannot use tools and response_model together
