### ISSUE TITLE
Add a new section called token usage and concepts. 

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#401]

**Comment by lazyhope** [comment]
Hi! I'd like to propose an enhancement regarding the tracking of token usage, as tokens consumed when all retries failed are not accounted for in the current implementation. 

Would it be feasible to introduce a `usage` attribute tied to each patched `client`, similar to the approach taken by `outlines` as demonstrated [here](https://outlines-dev.github.io/outlines/reference/models/openai/#monitoring-api-use)? This could also eliminate the need for the verbose `model._raw_response.usage`. 

Looking forward to your thoughts on this. Thank you!
