### ISSUE TITLE
Using Instructor as a wrapper blocks the API from sending `response.usage.total_tokens`

### ISSUE THREAD

**Issue by phatlast96** [jxnl/instructor#410]
- [x] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [x] gpt-4
- [ ] Other (please specify)

**Describe the bug**
I'm using Instructor as a wrapper for my OpenAPI. Due to costs, I want to get the  `response.usage.total_tokens` returned by the OpenAPI to use for billing purposes. I am unable to due to the wrapper blocking it.

**To Reproduce**
Steps to reproduce the behavior, including code snippets of the model and the input data and openai response.

**Expected behavior**

**Screenshots**

**Comment by jxnl** [comment]
https://jxnl.github.io/instructor/concepts/raw_response/ 


```python
import instructor

from openai import OpenAI
from pydantic import BaseModel

client = instructor.patch(OpenAI())


class UserExtract(BaseModel):
    name: str
    age: int


user: UserExtract = client.chat.completions.create(
    model="gpt-3.5-turbo",
    response_model=UserExtract,
    messages=[
        {"role": "user", "content": "Extract jason is 25 years old"},
    ],
)

print(user._raw_response)
"""
ChatCompletion(
    id='chatcmpl-8pOAsSOIHAmngMBBki3BLN3p552L0',
    choices=[
        Choice(
            finish_reason='stop',
            index=0,
            logprobs=None,
            message=ChatCompletionMessage(
                content=None,
                role='assistant',
                function_call=FunctionCall(
                    arguments='{\n  "name": "Jason",\n  "age": 25\n}',
                    name='UserExtract',
                ),
                tool_calls=None,
            ),
        )
    ],
    created=1707258346,
    model='gpt-3.5-turbo-0613',
    object='chat.completion',
    system_fingerprint=None,
    usage=CompletionUsage(completion_tokens=16, prompt_tokens=73, total_tokens=89),
)
"""
```
