### ISSUE TITLE
Iterables extraction not working in 0.5.0

### ISSUE THREAD

**Issue by jacoverster** [jxnl/instructor#412]
- [x] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [x] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [x] gpt-4
- [ ] Other (please specify)

**Describe the bug**
Extracting iterables not working.

**To Reproduce**
Python 3.12.1
Pydantic 2.6.1

The code below works on 0.4.0 but not on 0.5.0.
```
from openai import OpenAI

client = instructor.patch(OpenAI())


class UserDetail(BaseModel):
    name: str
    age: int


Users = Iterable[UserDetail]

users: Users = client.chat.completions.create(
    model="gpt-4",
    response_model=Users,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old, James is 3 years old",
        },
    ],
)  # type: ignore
users
```

**Expected behavior**
The expected output (as achieved in 0.4.0) is:
`[UserDetail(name='Jason', age=25), UserDetail(name='James', age=3)]`

The output in 0.5.0 is:
`IterableUserDetail()`

**Screenshots**
N/A

**Comment by jxnl** [comment]
verified! Till take a look at this. not sure how the tests didnt pick this up

**Comment by jxnl** [comment]
I noticed that we were testing the streaming case but not the non-streaming case.

**Comment by jacoverster** [comment]
Great stuff! Thanks

**Comment by jxnl** [comment]
@jacoverster can update to 0.5.2 please let me know if theres any issues, I'm stuck in meetings all day
