### ISSUE TITLE
Required fields cause OpenAPI specification errors

### ISSUE THREAD

**Issue by Shakakai** [jxnl/instructor#414]
- [x ] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [x] gpt-4
- [ ] Other (please specify)

**Describe the bug**
If you use a pydantic.Field with the attribute `required` set to True, the generated OpenAPI specification passed to OpenAI (boy don't we wish those names weren't so similar) contains invalid `required=True` fields in the JSON specification.

**To Reproduce**
Using Instructor 0.4.8:

``` python
# Create a model with required fields
class BlogPost(OpenAISchema):
    title: str = Field(
        description="Title of the blog post. Must be less than 100 characters.", 
        required=True
    )
    content: str = Field(
        description="Content of the blog post. Must be written in markdown.", 
        required=True
    )

client.chat.completions.create(**{"model": "gpt-4",
        "response_model": BlogPost,
        "messages": [
            {
                "role": "system",
                "content": "You are an AI journalist.",
            },
            {
                "role": "user",
                "content": "Please write a blog post about LLM prompt engineering",
            },
        ]}
  )
```

When run, I receive the following error:

```
Traceback (most recent call last):
  File "/Users/todd.cullen/Projects/syncom/syncom/interop/llm.py", line 15, in completion
    return client.chat.completions.create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/instructor/patch.py", line 392, in new_chatcompletion_sync
    response = retry_sync(
               ^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/instructor/patch.py", line 300, in retry_sync
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 659, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1180, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 869, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/todd.cullen/Projects/syncom/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 960, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "Invalid schema for function 'BlogPost': True is not of type 'array'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Expected behavior**

I'd expect to receive an instance of the BlogPost class back, filled out by the LLM. 

**Screenshots**

Check out the openai_schema shown in the debugger. You'll notice it has a `required` on the title property where that property should not exist. The OpenAPI spec expected `required` to be a list at the object level not the property level.

![Screenshot 2024-02-07 at 3 59 17 PM](https://github.com/jxnl/instructor/assets/54981/300b3088-1bfa-46fe-9aa1-ee5a42cb1a6a)

**Comment by Shakakai** [comment]
I'm not sure where I picked up the idea that a pydantic.Field has a `required` attribute (probably Co-Pilot autocomplete). It does not. However, I still think its bad behavior to pass arbitrary properties from pydantic.Field through to the OpenAPI schema for OpenAI.

**Comment by jxnl** [comment]
>I still think its bad behavior to pass arbitrary properties from pydantic.Field through to the OpenAPI schema for OpenAI.

The whole point is to pass those things to the schema to open AI. That's how we define prompts. Everything is required by default. 

or its `Optional[T] = Field(default=None)`

**Comment by Shakakai** [comment]
I'm trying to make sure I understand your response. Are you saying that you intend for this to be valid?

```python
class ExampleResponse(BaseModel):
    name: str = Field(my_whacky_property="whatever-value", description="The examples name")
```

My confusion is that `my_whacky_property` isn't in the JSON Schema spec (there's about ~20 properties supported: https://www.learnjsonschema.com/2020-12/validation/enum/) so I expected it to either trigger an error or to be ignored when generating the JSON schema for function calling.

If I put together a PR to restrict the attributes that get used to create the JSON Schema for function calling, would you merge it or is this error irrelevant?
