### ISSUE TITLE
Invalid JSON: EOF on example code for example of table extraction with GPT-V

### ISSUE THREAD

**Issue by duckduckgrayduck** [jxnl/instructor#456]
- [X] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [X] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [X] gpt-4   (vision-preview)
- [ ] Other (please specify)

**Describe the bug**
I tried running the code in the example here: 
https://jxnl.github.io/instructor/examples/extracting_tables/#top-10-grossing-apps-in-october-2023-ireland-for-ios-platforms

**To Reproduce**
Steps to reproduce the behavior, including code snippets of the model and the input data and openai response.
I've installed all of the dependencies and ran it using python3 main.py 

**Expected behavior**
I expect to see the two resulting tables like those in the tutorial. 

**Screenshots**
![JSONError](https://github.com/jxnl/instructor/assets/102841251/42eebc9c-6e68-47fd-83e0-71eeec881d37)

I can confirm I have gpt-4-vision-preview working using a different really simple script:
![Table](https://github.com/jxnl/instructor/assets/102841251/bcf8a445-c47c-4199-8cf0-8ea9734683b7)

**Comment by jxnl** [comment]
I'm moving and unitesting the hub examples can you try of this is working better?

https://jxnl.github.io/instructor/hub/tables_from_vision/

**Comment by duckduckgrayduck** [comment]
@jxnl This succeeds for me
