### ISSUE TITLE
Streaming raw response

### ISSUE THREAD

**Issue by ranfdev** [jxnl/instructor#462]
**Is your feature request related to a problem? Please describe.**
I'd like to stream the raw response when GPT decides to not call the passed tool. I'm setting
```python
client.chat.completions.create(
    ...
    stream=True,
    response_model=SearchTool,
)
```
But I get
`NotImplementedError: stream=True is not supported when using response_model parameter for non-iterables`

**Describe the solution you'd like**
I'd like an option `stream_raw`, so that I can always stream the raw response.

**Additional context**
I don't want the response to be parsed as a tool call at all costs. I need the raw response most of the time. I just want to parse the tool call when GPT decides to actually call the tool

**Comment by jxnl** [comment]
You should just use normal function calling then

**Comment by ranfdev** [comment]
I ended up using the utilities from `instructor.function_calls` to easily generate the tools schemas, then passing the schemas to a standard, unpatched OpenAI client.

Finally, If the response is a function call, I just parse it with pydantic.

**Comment by jxnl** [comment]
perfect!
