### ISSUE TITLE
Add Claude 3 into Instructor

### ISSUE THREAD

**Issue by phatlast96** [jxnl/instructor#479]
**Is your feature request related to a problem? Please describe.**
I'd love to use Instructor for a Claude as well so my users are able to have options between OpenAI and Anthropic.

**Describe the solution you'd like**
Claude 3 API now has the capabilities to produce structured JSON. It'd be great to include that into Instructor.

**Describe alternatives you've considered**

**Additional context**
<img width="319" alt="Screenshot 2024-03-04 at 7 30 33 AM" src="https://github.com/jxnl/instructor/assets/10504024/befa40fd-26b1-4111-b676-ad7978f4746d">

**Comment by lazyhope** [comment]
Just use `litellm` proxy:
```bash
litellm --port 8000 --model claude-3-sonnet-20240229  # or claude-3-opus-20240229
```

Once the local proxy is running, patch the client in the following way and use it as usual:
```python
import instructor
from openai import OpenAI
from pydantic import BaseModel

# Enables `response_model`
client = instructor.patch(OpenAI(api_key="anything", base_url="http://0.0.0.0:8000"))


class UserDetail(BaseModel):
    name: str
    age: int


user = client.chat.completions.create(
    model="gpt-3.5-turbo",
    response_model=UserDetail,
    messages=[
        {"role": "user", "content": "Extract Jason is 25 years old"},
    ],
)

assert isinstance(user, UserDetail)
assert user.name == "Jason"
assert user.age == 25
```

**Comment by atomobianco** [comment]
@phatlast96 it seems you got covered starting with [release 0.6.5](https://github.com/jxnl/instructor/releases/tag/0.6.5)
