### ISSUE TITLE
docs: improve docs on logging 

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#480]
I like the added login page in concepts. that answer: https://github.com/jxnl/instructor/discussions/350 in better fashion.

**Comment by leobeeson** [comment]
Do you mean adding logging details to [this page](https://jxnl.github.io/instructor/concepts/raw_response/) or would you like a new page in concepts for logging?

**Comment by jxnl** [comment]
lets make a new one called "Logging"

**Comment by jxnl** [comment]
I thought this was enough



```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by jxnl** [comment]
turns out it exited but i didnt linked the pages
