### ISSUE TITLE
Support for older python versions?

### ISSUE THREAD

**Issue by kalpit-konverge** [jxnl/instructor#495]
I was wondering if you can support an older version of python, say , 3.8. Is it possible? Any specific features that will make it compatible to older versions?

**Comment by jxnl** [comment]
mind making a PR that adds 3.8 and 3.9 to the test matrix? 
I feel like it was around annotations but have not checked i na while

**Comment by jxnl** [comment]
https://github.com/jxnl/instructor/pull/496
