### ISSUE TITLE
Extracting docstring from nested Pydantic Objects

### ISSUE THREAD

**Issue by FridrikLax** [jxnl/instructor#500]
```
class Workflow(OpenAISchema):
    """Request to the assistant to help the case to flow to the next step in a workflow."""
    workflow: str

class Assign(Workflow):
    """Request to assign a case to another user."""
    target_user: str
```

The `openai_schema` class method only accounts for the docstring of Assign, but not the parent (Workflow).

Current output:
`
{'function': {'description': 'Request to assign a case to another user.',
               'name': 'Assign',
               'parameters': {'properties': {'target_user': {'title': 'Target '
                                                                      'User',
                                                             'type': 'string'},
                                             'workflow': {'title': 'Workflow',
                                                          'type': 'string'}},
                              'required': ['target_user', 'workflow'],
                              'type': 'object'}},
  'type': 'function'}
`

Desired output:
`
{'function': {'description': 'Request to the assistant to help the case to flow to the next step in a workflow. Request to assign a case to another user.',
               'name': 'Assign',
               'parameters': {'properties': {'target_user': {'title': 'Target '
                                                                      'User',
                                                             'type': 'string'},
                                             'workflow': {'title': 'Workflow',
                                                          'type': 'string'}},
                              'required': ['target_user', 'workflow'],
                              'type': 'object'}},
  'type': 'function'}
`

**Comment by wehnsdaefflae** [comment]
that would be great indeed. in fact i thought a function description would be essential to proper function selection in the first place.

**Comment by jxnl** [comment]
thats not really how inheretance works, can you submit a PR for what that might look like? 

what if they do  params in the docstring
