### ISSUE TITLE
When retrying, Pydantic validation errors are included in the prompt twice in Mode.TOOLS

### ISSUE THREAD

**Issue by ilyanekhay-uta** [jxnl/instructor#513]
- [X] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [X] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**
When a retry happens, the text "Recall the function correctly, fix the errors" is included in the prompt twice together with the whole Pydantic exception message.

**To Reproduce**
Use Mode.TOOLS.
Make a Pydantic model such that the LLM fails to respond to it correctly and a retry happens.
Observe OpenAI logs and note that the error message is included twice.

**Expected behavior**
I'd expect the exception message to only be included once.

**Possible easy fix?**
Is it possible that the "if" in this line should be an "elif"? 

https://github.com/jxnl/instructor/blob/main/instructor/retry.py#L39

The current logic is:
```
if mode == Mode.TOOLS:
    ...

if mode == Mode.MD_JSON:
    ...
else:
    ...
```

With this logic, the execution goes through the first `if:` as well as through `else:`, serializing the exception twice.

**Comment by jxnl** [comment]
shoot can you PR a fix?
