### ISSUE TITLE
Anthropic Parsing Lists of non-objects

### ISSUE THREAD

**Issue by Cruppelt** [jxnl/instructor#515]
- [x] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other - claude-3-opus-20240229 (Model does not affect this bug)

**Describe the bug**
Code hard fails on trying to get the $ref key.

/instructor/anthropic_utils.py", line 88, in _add_params
    _resolve_reference(references, details["items"]["$ref"]),
                                   ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: '$ref'

**To Reproduce**
```python
from typing import List

import anthropic
import instructor
from pydantic import BaseModel


class CountedNumbers(BaseModel):
    numbers: List[int]


def main():
    anthropic_client = instructor.patch(
        create=anthropic.Anthropic().messages.create, mode=instructor.Mode.ANTHROPIC_TOOLS
    )

    user_response = anthropic_client(
        model="claude-3-opus-20240229",
        max_tokens=1024,
        max_retries=0,
        system="Count all the numbers up to the given number.",
        messages=[
            {
                "role": "user",
                "content": "3",
            }
        ],
        response_model=CountedNumbers,
    )  # type: ignore

    print(user_response.model_dump_json(indent=2))


if __name__ == "__main__":
    main()
```


**Expected behavior**
I'd expect to get a pydantic model with model_dump_json like

```json
{
  "numbers": [
    1,
    2,
    3
  ]
}
```

**Comment by Cruppelt** [comment]
@jxnl I have a local fix for this, looks like some permission issue to push for a PR?

**Comment by shreya-51** [comment]
hey! check this out: https://github.com/jxnl/instructor/pull/521

**Comment by Cruppelt** [comment]
> hey! check this out: #521

Awesome, appreciate it! Am I able to get access to push? few prompt clean up things I'd like to PR

**Comment by jxnl** [comment]
I'll get this in and you can fork and make a PR

**Comment by akarshghale** [comment]
Hi guys,

Facing this issue, is there any fix implemented other than the Opus suggestion?

**Comment by jxnl** [comment]
@akarshghale can you update and then try `mode=Mode.ANTHROPIC_JSON`

**Comment by akarshghale** [comment]
> @akarshghale can you update and then try `mode=Mode.ANTHROPIC_JSON`

Yep it is working now!

**Comment by jxnl** [comment]
great we'll have better support in the future, we'll set it to default in v1.0
