### ISSUE TITLE
Instructor 0.6.5 fails to import due to missing dependency (xmltodict)

### ISSUE THREAD

**Issue by ntaylorwss** [jxnl/instructor#516]
- [x] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [x] I have tried asking for help in the community on discord or discussions and have not received a response.
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**
Instructor 0.6.5 is un-importable due to a missing dependency in `instructor/anthropic_utils.py`: `xmltodict`.

**To Reproduce**

1. `pip install instructor==0.6.5`
2. `python -c 'import instructor'`
3. `ModuleNotFoundError: No module named xmltodict`

**Comment by jpetrantoni** [comment]
Also facing this, had to run `pip install xmltodict`

**Comment by jxnl** [comment]
I’m I thought we sue importlib. Are you able to submit a fix to only import when we use anthropic tools.

**Comment by jxnl** [comment]
interesting ok, updated 0.6.6 to not import unless anthropic is used

**Comment by jpetrantoni** [comment]
Still facing the issue however updating pyproject.toml fixes it. I tested both `pip install instructor` (no anthropic or xmltodict installed) and `pip install 'instructor[anthropic]' successfully imports anthropic and xmltodict


<img width="1291" alt="Screenshot 2024-03-20 at 9 17 18 PM" src="https://github.com/jxnl/instructor/assets/79169021/c76906ec-ea1b-468a-b4ef-f942f908bed0">
