### ISSUE TITLE
In Mode.PARALLEL_TOOLS, if the model doesn't invoke a function an error is returned

### ISSUE THREAD

**Issue by mwildehahn** [jxnl/instructor#528]
- [x] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**
The issue is here: https://github.com/jxnl/instructor/blob/726ca86c958d5e129bddf821dcc39ece4c2865a0/instructor/dsl/parallel.py#L41. If there are no tool calls (since we can't force gpt-* to make a tool call) this line will fail.

I have a local fix which does:

```
--- a/instructor/dsl/parallel.py
+++ b/instructor/dsl/parallel.py
@@ -20,6 +20,11 @@ from instructor.mode import Mode

 T = TypeVar("T", bound=OpenAISchema)

+class MissingToolCall(Exception):
+    def __init__(self, response: Any, *args: Any) -> None:
+        super().__init__(*args)
+        self.response = response
+

 class ParallelBase:
     def __init__(self, *models: Type[OpenAISchema]):
@@ -38,6 +43,9 @@ class ParallelBase:
         #! We expect this from the OpenAISchema class, We should address
         #! this with a protocol or an abstract class... @jxnlco
         assert mode == Mode.PARALLEL_TOOLS, "Mode must be PARALLEL_TOOLS"
+        if not response.choices[0].message.tool_calls:
+            raise MissingToolCall(response)
+
         for tool_call in response.choices[0].message.tool_calls:
             name = tool_call.function.name
             arguments = tool_call.function.arguments
```

so I can at least catch the error and return the response but not a great dx.

**Comment by jxnl** [comment]
i think it makes sense to raise a custom exception, then people can catch it!
what do you think?
