### ISSUE TITLE
Issues with junk after document for anthropic. 

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#529]
FAILED tests/anthropic/test_simple.py::test_list - xml.parsers.expat.ExpatError: junk after document element: line 2, column 0
FAILED tests/anthropic/test_simple.py::test_nested_list - xml.parsers.expat.ExpatError: junk after document element: line 2, column 0

When you run the tests, we get some errors.

**Comment by SalamanderXing** [comment]
I ran into this running the example on the blog: https://python.useinstructor.com/blog/2024/03/20/announcing-anthropic-support/

**Comment by Cruppelt** [comment]
https://github.com/jxnl/instructor/pull/531
