### ISSUE TITLE
No overloads for "create" match the provided arguments  - Pylance complains on brand new project

### ISSUE THREAD

**Issue by aaronvg** [jxnl/instructor#533]
Any tips on how to setup pylance to work with instructor properly?

I set up a new poetry project, installed instructor, copied the code snippet from the README, but it seems the patch doesnt return the right type back.

- Using python 3.11

<img width="782" alt="image" src="https://github.com/jxnl/instructor/assets/5353992/5e85ce48-5eed-46cb-97ea-d30d3088890a">

I suppose we can't really fix `No overloads for "create" match the provided arguments
  Argument types: (Literal['gpt-4'], type[UserInfo], list[dict[str, str]])` since OpenAI literally doesn't implement that property.

Interpreter is also set correctly:
<img width="741" alt="image" src="https://github.com/jxnl/instructor/assets/5353992/b6d297fd-2d72-4251-b701-336353fe78f1">

VSCode settings are set to "basic" typechecking
`"python.analysis.typeCheckingMode": "basic",`

Is it expected to not have the type completion on the responses or did I setup something incorrectly?

**Comment by jxnl** [comment]
we ran into some issues we hope to fix in 1.0 with a new client thats just, but this is unforchunatly a known issue right now :(

**Comment by noxan** [comment]
similar issue when you patch the method (`patch(create=...)`) where all the default openai parameters trigger a `error: Arguments for ParamSpec "T_ParamSpec@__call__" are missing (reportCallIssue)` warning.

**Comment by jxnl** [comment]
hope to fix this in 1.0 with #544
