### ISSUE TITLE
Amazon Bedrock support

### ISSUE THREAD

**Issue by austinmw** [jxnl/instructor#540]
Please add support for Amazon Bedrock 🤩

**Comment by jxnl** [comment]
I don't have any clients right now that are needing it so it's gonna have to wait unless someone contributes 😶

**Comment by jxnl** [comment]
now that we have 

instructor.from_*, anyone is welcome to add a instructor.from_bedrock

**Comment by jarrod-dexter** [comment]
Would it be possible to implement it for Claude as I anticipate this is the primary model most of us are using via Bedrock right now? I have almost zero experience but I believe it comes down to allowing AnthropicBedrock client to be passed to the from_anthropic method:

<img width="701" alt="image" src="https://github.com/jxnl/instructor/assets/95188999/9729fb8c-dcad-440c-936c-dc6972daf8e9">


Seems to be working for with this fix:

<img width="986" alt="image" src="https://github.com/jxnl/instructor/assets/95188999/a52aeb74-8640-4d70-ac00-2f82e6d3ec3c">

**Comment by jxnl** [comment]
sweet! ill take a PR for this

**Comment by shabie** [comment]
Would be great to have something that works with boto3 too. I am happy to make a PR.

**Comment by fer-git** [comment]
+1 need this, since Anthropic announced tools feature on Bedrock.

**Comment by jxnl** [comment]
this is done, you can either do bedrock anthropic client, or use litellms's bedrock/* models

**Comment by omeruth** [comment]
Is there support for Meta Models?

**Comment by psharma28** [comment]
How to make anthropic bedrock work with it? Below mentioned line throws error

`client = instructor.patch(boto3.client('bedrock-runtime',region_name=region))`

```
client = instructor.patch(boto3.client('bedrock-runtime',region_name=region))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/path/to/project/.venv/lib/python3.12/site-packages/instructor/patch.py", line 132, in patch
    func = client.chat.completions.create
           ^^^^^^^^^^^

  File "/path/to/project/.venv/lib/python3.12/site-packages/botocore/client.py", line 918, in __getattr__
    raise AttributeError(
AttributeError: 'BedrockRuntime' object has no attribute 'chat'
```
