### ISSUE TITLE
No module named 'anthropic' using OpenAISchema

### ISSUE THREAD

**Issue by ingli96** [jxnl/instructor#564]
- [x] This is an actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [x] gpt-4
- [ ] Other (please specify)

**Describe the bug**
I'm trying to use OpeAISchema to convert my pydantic models into functions definition and getting the error

```
fastapi-app_1  |   File "/app/app/services/service_openai.py", line 3, in <module>
fastapi-app_1  |     from app.shemas import *
fastapi-app_1  |   File "/app/app/shemas.py", line 4, in <module>
fastapi-app_1  |     from instructor import OpenAISchema
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/__init__.py", line 2, in <module>
fastapi-app_1  |     from .process_response import handle_response_model
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/process_response.py", line 5, in <module>
fastapi-app_1  |     from instructor.dsl.iterable import IterableBase, IterableModel
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/dsl/__init__.py", line 4, in <module>
fastapi-app_1  |     from .validators import llm_validator, openai_moderation
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/dsl/validators.py", line 7, in <module>
fastapi-app_1  |     from instructor.client import Instructor
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/client.py", line 4, in <module>
fastapi-app_1  |     import anthropic
fastapi-app_1  | ModuleNotFoundError: No module named 'anthropic'
```

**To Reproduce**
openai>=1.16.1
instructor==1.0.0
no antropic installed

just import OpenAISchema

**Expected behavior**
no (ModuleNotFoundError: No module named 'anthropic') error

UPD:

just realized, you cant even use instructor.

fastapi-app_1  |   File "/app/app/services/service_openai.py", line 2, in <module>
fastapi-app_1  |     import instructor
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/__init__.py", line 2, in <module>
fastapi-app_1  |     from .process_response import handle_response_model
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/process_response.py", line 5, in <module>
fastapi-app_1  |     from instructor.dsl.iterable import IterableBase, IterableModel
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/dsl/__init__.py", line 4, in <module>
fastapi-app_1  |     from .validators import llm_validator, openai_moderation
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/dsl/validators.py", line 7, in <module>
fastapi-app_1  |     from instructor.client import Instructor
fastapi-app_1  |   File "/usr/local/lib/python3.10/site-packages/instructor/client.py", line 4, in <module>
fastapi-app_1  |     import anthropic
fastapi-app_1  | ModuleNotFoundError: No module named 'anthropic'

**Comment by jxnl** [comment]
please update to 1.0.1 it should be optional

**Comment by nickknyc** [comment]
awaiting it's appearance on PyPI
