### ISSUE TITLE
Pydantic/pydantic-core dependency conflict

### ISSUE THREAD

**Issue by timlod** [jxnl/instructor#571]
- [x] This is an actually a bug report.

**Describe the bug**
1.0.2 added the just-released pydantic-core 2.18.0 as a dependency. The most recent release of `pydantic` proper (2.6.4) pins to pydantic-core 2.16.3, so there is no corresponding release that works.

Not sure if 2.18.0 is actually required - using 2.16.0 as the minimum version fixes this.

**To Reproduce**
Install instructor 1.0.2 with pip (currently local as this release isn't yet on PyPi):
`pip install .`

**Expected behavior**
No dependency conflicts.

**Comment by jxnl** [comment]
https://pypi.org/project/instructor/ it shows up no?

**Comment by jxnl** [comment]
You'll need to update like so to support the new release thanks for calling this out
```
instructor>=1.0.2
pydantic>=2.7.0b01
```

**Comment by timlod** [comment]
> https://pypi.org/project/instructor/ it shows up no?

Now 1.0.3 is up, yes! When I tried, 1.0.2 was the release here, but 1.0.0 was the version on PyPi.
Perhaps there was some integration running which rejected the release from PyPi because of this?
Anyways, now it's all good - thanks!
