### ISSUE TITLE
Return multiple choices

### ISSUE THREAD

**Issue by kstathou** [jxnl/instructor#576]
**Describe the solution you'd like**
Thanks a lot for making this library, it's been super helpful! I am working on a text classification task and I wanted to get multiple parsed responses from a single `client.chat.completions.create` call using OpenAI's [n](https://platform.openai.com/docs/api-reference/chat/create#chat-create-n) parameter.

The following would only parse the first completion I believe:

```python
client.chat.completions.create_with_completion(
        model="gpt-3.5-turbo-0613",
        response_model=SinglePrediction,
        messages=[
            {
                "role": "user",
                "content": f"Classify the following text: {data}",
            },
        ],
        n=3,
    )
```

How would you recommend going on about it? Thank you!

**Comment by jxnl** [comment]
I think we can create a overload that does this thanks for the new sdk

**Comment by jxnl** [comment]
Will experiment with overloads.

**Comment by jxnl** [comment]
https://github.com/jxnl/instructor/pull/578

**Comment by NicolaiLolansen** [comment]
> #578

This was closed without merge, is this functionality working? It's a really nice feature to have if you want to extract multiple elements from a larger chunk of text, like menu items.

**Comment by josepablog** [comment]
Also interested in this feature

**Comment by NicolaiLolansen** [comment]
> Also interested in this feature

Did you look at the solution I posted? It seems to work very well for me.

**Comment by josepablog** [comment]
ohhh.. I didn't understand it at first.   

I'll think about it, I think I may be able to solve my issue with prompting: I'm outputting a  list to begin with, and I don't think a list of lists.  I am just trying to make sure that the list is long enough.

thanks for getting back to me!

**Comment by thomasnormal** [comment]
Pydantic also supports minimum list lengths: https://github.com/annotated-types/annotated-types?tab=readme-ov-file#minlen-maxlen-len
```
from annotated_types import Len
from pydantic import BaseModel

class Foo(BaseModel):
  my_list: Annotated[list[str], Len(min_length=5, max_length=5)]
```

**Comment by thomasnormal** [comment]
To be clear, this feature would still be incredibly useful to have.
When you force the model to output a certain list length, you get answers that are "influences" by each other.
Lots of state of the art LLM based methods require you to create 1000 answers independently, or more, and you can save a lot of money by using `n=...` rather than sending individual requests.
