### ISSUE TITLE
Add support for cohere models in Instructor

### ISSUE THREAD

**Issue by lidiyam** [jxnl/instructor#584]
**Is your feature request related to a problem? Please describe.**
Add support for cohere models in Instructor

**Describe the solution you'd like**
Command-R and Command-R-plus models are finetuned for tool use and have the capabilities to produce structured JSON. It'd be great to include that into Instructor.

**Describe alternatives you've considered**
`.from_litellm` technically supports any hf model, but requires loading & inferencing 35B+ param models locally. It'd be nice to leverage cohere's `/chat` endpoint. 

**Additional context**
I already have some working code to do this (heavily inspired by instructor's philosophy), just need to clean it up and merge it in here.

**Comment by ionflow** [comment]
@lidiyam can you confirm that with this fix the cohere client works for you? or do you specifically need it to work with LiteLLM client?

https://github.com/jxnl/instructor/pull/761
