### ISSUE TITLE
Add support for Google Gemini

### ISSUE THREAD

**Issue by danaiamirali** [jxnl/instructor#592]
**Is your feature request related to a problem? Please describe.**
I'm currently working on a project using Gemini, and if this library supported Gemini that would've been great. Will likely be building my own instructor-esque solution to get structured output.

**Describe the solution you'd like**
Adding support for Gemini.

**Comment by jxnl** [comment]
If you intend to build something instructor esqu, would love a contribution if you're willing.

**Comment by danaiamirali** [comment]
Definitely willing to work on this. Unfortunately, it appears that at least as of now most forms of Gemini lacks any API parameters like OpenAI's `response_format`. Gemini 1.5 Pro, though, (which is luckily the model I will be using) does offer a [JSON formatted response](https://ai.google.dev/docs/gemini_api_overview#json). I'll look into that and hopefully contribute.

**Comment by jxnl** [comment]
Yeah, I think what might need to happen is to find something that goes from PyDantic or JSON schema to Gemini's RPC model. which is a bit of a pain and why we avoided it so far. It might make sense to just have a ask for Jason mode in Gemini.

**Comment by Vasilije1990** [comment]
could this work with litellm or is it another type of an integration issue?

**Comment by danaiamirali** [comment]
From my (very limited) knowledge of LiteLLM, their completions don't seem to support structured output? 

I did end up making a hasty structured output solution for Gemini 1.5 Pro with the Gemini REST API (because their Python SDK unfortunately does not support JSON outputs fsr) for a Hackathon. Will look into cleaning it up and applying it to this repo for a PR if using the REST API is fine @jxnl.
