### ISSUE TITLE
docstring-parser 0.16

### ISSUE THREAD

**Issue by palako** [jxnl/instructor#598]
**Is your feature request related to a problem? Please describe.**
It's just a minor annoyance. docstring-parser 0.15 has a few deprecated things that clutter the debug logs.

**Describe the solution you'd like**
a bump in the docstring-parser version to 0.16

**Describe alternatives you've considered**
Keep putting up with the annoyance.

**Additional context**
docstring-parser = "^0.15" in project.toml will update minor versions but won't go to 0.16

**Comment by jxnl** [comment]
sounds good, feel pree to make PR and we'll fix in next deploy
