### ISSUE TITLE
Is there a way to parse JSON in non-strict mode?

### ISSUE THREAD

**Issue by voberoi** [jxnl/instructor#612]
**Is your feature request related to a problem? Please describe.**
Anthropic's models regularly have control characters in their strings, producing invalid JSON that causes validation to fail.

**Describe the solution you'd like**
I'd like the option to parse JSON by passing strict=False as the [docs over here](https://docs.python.org/3/library/json.html#json.JSONDecoder) indicate I can.

<img width="798" alt="CleanShot 2024-04-17 at 23 09 51@2x" src="https://github.com/jxnl/instructor/assets/26339/6dbc2af4-fa4a-4c15-ab07-26fbfb871846">

**Describe alternatives you've considered**
- Catching the Pydantic validation error, checking if it the type is `json_invalid`, and then parsing the JSON on my own.
- I've poked around the codebase. It looks like [this was possible at one point](https://github.com/jxnl/instructor/pull/75) and the current code [has docstrings indicating that this is possible but `strict` is not a valid param](https://github.com/jxnl/instructor/blob/0a849828b9efd004888df2004de56683e02d593d/instructor/patch.py#L94).

I can't figure out how to do this or if this functionality you intend the library to have (or once did but don't anymore).

**Comment by sigren** [comment]
I second

**Comment by voberoi** [comment]
It looks like instructor uses Pydantic's `model_validate_json`. It has a `strict` param but doesn't have the same semantics as the standard library's `strict` when parsing json.

It's possible to do `model_validate_json(json.load(...))` -- is that something you'd consider allowing?

It's less performant and it won't work in a streaming context, but it gives clients an out when models misbehave with control characters.

**Comment by jxnl** [comment]
I'd actually rather expose `strict=False` to the create call's patch, let me try to spend 10 minutes on this, if you dont hear back i'd take a PR too!

**Comment by jxnl** [comment]
https://github.com/jxnl/instructor/pull/618 please take a look

**Comment by voberoi** [comment]
Hey! Thanks for your help on this.

Continuing the discussion here since #618 is merged.

I'm happy to provide a patch for this functionality.

What do you think of merging Pydantic and `json.load`'s "strict" semantics as in this example here: https://github.com/jxnl/instructor/pull/618#issuecomment-2069506854

Or would you prefer to split these up?

**Comment by jxnl** [comment]
i think it makes sense esp since control characters are an issue

**Comment by voberoi** [comment]
Great -- will merge those semantics. I'll take a crack at a patch.

**Comment by voberoi** [comment]
Fixed in #644.
