### ISSUE TITLE
Instructor with llmlite doenst support vision for Claude 3 Haiku and Sonnet models

### ISSUE THREAD

**Issue by enoch3712** [jxnl/instructor#617]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other (Claude 3 vision)

**Describe the bug**
Instructor with llmlite doesn't support vision for Claude 3 Haiku and Sonnet models

Information about the models is here:
https://docs.litellm.ai/docs/providers/anthropic

#claude-3-opus-20240229 - ok
#claude-3-haiku-20240307 - not ok
#claude-3-sonnet-20240229 - not ok

**To Reproduce**
```
# change model to "claude-3-haiku-20240307" or "claude-3-sonnet-20240229"
 resp = instructor.from_litellm(litellm.completion).chat.completions.create(
                model='claude-3-opus-20240229',
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": "What’s in this image?"
                            },
                            {
                                "type": "image_url",
                                "image_url": {
                                    "url": "data:image/jpeg;base64," + encode_image(file)
                                }
                            }
                        ]
                    }
                ],
                response_model=response_model,
            )

```
**Expected behavior**
Should return a response, instead raises the exception on the screenshot

**Screenshots**
![image](https://github.com/jxnl/instructor/assets/9283394/ee799eca-b864-4662-8d69-71801f823c67)

**Comment by ZhymabekRoman** [comment]
Workaround for now is to use two Anthropic's instances, one is patched with instructor another without.

**Comment by enoch3712** [comment]
> Workaround for now is to use two Anthropic's instances, one is patched with instructor another without.

Can you give an example? 

Thank you,

**Comment by enoch3712** [comment]
> Workaround for now is to use two Anthropic's instances, one is patched with instructor another without.

Thank you.


Is this something that can be solved easily?

Or is an known issue that you persist?

**Comment by pablopalafox** [comment]
Would be cool to support bedrock as well!
