### ISSUE TITLE
Async Retry is broken

### ISSUE THREAD

**Issue by lazyhope** [jxnl/instructor#628]
- [x] This is actually a bug report.

**What Model are you using?**

- [x] Claude 3

**Describe the bug**
`e.attempt_number` doesn't actually exists, the following lines would raise `AttributeError: 'pydantic_core._pydantic_core.ValidationError' object has no attribute 'attempt_number'`

https://github.com/jxnl/instructor/blob/2b80e13215fbe0ee971316a6cda09136f1c10a79/instructor/retry.py#L230-L239

**To Reproduce**

Reproduce in the interpreter:

```python
from typing import Annotated

import instructor
from anthropic import AsyncAnthropic
from pydantic import BaseModel, field_validator


client = instructor.from_anthropic(AsyncAnthropic(), mode=instructor.Mode.ANTHROPIC_JSON, model="claude-3-haiku-20240307")

class User(BaseModel):
    name: str

    @field_validator("name")
    def validate_gender(cls, v, info):
        raise ValueError("You will never succeed")

await client.chat.completions.create(
    max_tokens=4096,
    temperature=0,
    messages=[{"role": "user", "content": "Extract Jason is 25 years old"}],
    response_model=User,
)
```

**Comment by lazyhope** [comment]
Also Jason @jxnl could you please explain the purpose of the following lines?

https://github.com/jxnl/instructor/blob/2b80e13215fbe0ee971316a6cda09136f1c10a79/instructor/retry.py#L227-L234

It seems like these lines are redundant, as `tenacity` will always catch any raised exceptions for us

**Comment by lazyhope** [comment]
Add a fix to this in my last PR #622

**Comment by lazyhope** [comment]
@jxnl Hi Jason thanks for reviewing my PR and merge it. Before this issue is completely closed could I ask why is there a InstructorRetryError inside the try clause, it doesn't seem necessary to raise it until the except clause?

**Comment by jxnl** [comment]
Probs me being dumb.

**Comment by lazyhope** [comment]
😂
