### ISSUE TITLE
`anthropic` should no longer be an extras dependency

### ISSUE THREAD

**Issue by arcaputo3** [jxnl/instructor#646]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other (please specify)

**Describe the bug**
Running `from instructor import patch` leads to a `ModuleNotFoundError: No module named 'anthropic'`.

**To Reproduce**
- Create a `poetry` environment with `instructor = "^1.2.5"`
- Run `from instructor import patch`

**Expected behavior**
`patch` should be importable for reverse compatibility as this change breaks pipelines.

**Screenshots**
```
ImportError while importing test module 'C:\Users\rcaputo3\tjc\tjc-databricks\tests\instructor\test_base.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\..\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests\instructor\test_base.py:3: in <module>
    from tjc_databricks.instructor.base import validate_length
tjc_databricks\instructor\__init__.py:3: in <module>
    from instructor import patch
..\..\AppData\Local\pypoetry\Cache\virtualenvs\tjc-databricks-lKdFldj--py3.10\lib\site-packages\instructor\__init__.py:4: in <module>
    from .process_response import handle_response_model
..\..\AppData\Local\pypoetry\Cache\virtualenvs\tjc-databricks-lKdFldj--py3.10\lib\site-packages\instructor\process_response.py:6: in <module>
    from instructor.dsl.iterable import IterableBase, IterableModel
..\..\AppData\Local\pypoetry\Cache\virtualenvs\tjc-databricks-lKdFldj--py3.10\lib\site-packages\instructor\dsl\__init__.py:1: in <module>
    from .iterable import IterableModel
..\..\AppData\Local\pypoetry\Cache\virtualenvs\tjc-databricks-lKdFldj--py3.10\lib\site-packages\instructor\dsl\iterable.py:6: in <module>
    from instructor.function_calls import OpenAISchema
..\..\AppData\Local\pypoetry\Cache\virtualenvs\tjc-databricks-lKdFldj--py3.10\lib\site-packages\instructor\function_calls.py:18: in <module>
    from instructor.utils import classproperty, extract_json_from_codeblock
..\..\AppData\Local\pypoetry\Cache\virtualenvs\tjc-databricks-lKdFldj--py3.10\lib\site-packages\instructor\utils.py:16: in <module>
    from anthropic.types import Usage as AnthropicUsage
E   ModuleNotFoundError: No module named 'anthropic'
```

**Comment by arcaputo3** [comment]
I can confirm that `instructor = "1.2.4"` works as expected and that `1.2.5` introduced the breaking change.

**Comment by bencrouse** [comment]
I'm hitting this too, Is making `anthropic` a full dependency the desired state? What if you aren't using Anthropic and don't need the extra dependency?

**Comment by arcaputo3** [comment]
This looks pretty good: https://github.com/jxnl/instructor/commit/3ee7a2819d7d1be6522ee8ae0f4bdc1fd224a002

Installing `instructor = { git = "https://github.com/jxnl/instructor", branch = "main" }` allows `patch` to be imported properly with no extra dependency.

**Comment by noxan** [comment]
should be fixed with https://github.com/jxnl/instructor/pull/645
