### ISSUE TITLE
Achieve seamless connection between program code and LLM prompt

### ISSUE THREAD

**Issue by klb3713** [jxnl/instructor#653]
**Is your feature request related to a problem? Please describe.**
My Feature request has nothing to do with the current issue

**Describe the solution you'd like**
The current capability is one-way, i.e. formatting the output of LLM into program objects. The upgrade I would like to suggest is two-way. For example, you can execute the LLM call as a function, pass in the program object as a parameter, automatically convert the program object into a prompt internally, then execute the LLM call, and then format the return result into a program. object.
This feature will enable seamless execution of program code and LLM prompts. This is great!

**Describe alternatives you've considered**

**Additional context**

**Comment by Mr-Ruben** [comment]
If this is not what you are after, could you show us some code?


```
class Output(BaseModel):
    name: str
    age: int
```    

Let's imagine we just have the object.

```
# the object
person=Output(age=33,name="Sam")

# call only with object 
r=call_llm_with_class(   
                  prompt=str(person),
                  response_model=type(person),
                  )

print(r.output)
# {'name': 'Sam', 'age': 33}
```

This is actual output, not pseudo-code.

call_llm_with_class is just a wrapper

**Comment by ivanleomk** [comment]
Closing this issue for now due to a lack of activity.
