### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by bryanhpchiang** [jxnl/instructor#670]
I would mention it in the Discord but I can't even join

Discord link on this page is broken: https://python.useinstructor.com/

<img width="520" alt="image" src="https://github.com/jxnl/instructor/assets/98059440/e902fff7-f25b-4398-af38-6c4cf073147c">

**Comment by denisergashbaev** [comment]
yes, i was also wondering  what the proper discord link is

**Comment by jlondonobo** [comment]
The problem with the Discord link was addressed in #690. This issue can be closed.

**Comment by ivanleomk** [comment]
Closing this issue since the discord link has been fixed, thanks @jlondonobo! :)

**Comment by ivanleomk** [comment]
Closing this issue since the discord link has been fixed, thanks @jlondonobo! :)
