### ISSUE TITLE
`DeprecationWarning` raised on `import instructor` vs. use of `Mode.FUNCTIONS`

### ISSUE THREAD

**Issue by boydgreenfield** [jxnl/instructor#679]
- [X] This is actually a bug report.
- ~I am not getting good LLM Results
- ~I have tried asking for help in the community on discord or discussions and have not received a response.~
- ~I have tried searching the documentation and have not found an answer.~

**What Model are you using?**
N/A

**Describe the bug**
Instructor is raising a `DeprecationWarning` on import vs. access of the `Mode.FUNCTIONS` mode.

**To Reproduce**
```python3
import warnings
warnings.simplefilter("default")
import instructor
```

**Expected behavior**
A `DeprecationWarning` is only raised on access to `Mode.FUNCTIONS`

**Screenshots**
N/A

**Comment by avyfain** [comment]
@boydgreenfield what version was this on? Can't reproduce on Python 3.12.1 with instructor 1.3.3

**Comment by tconbeer** [comment]
I can't repro with the snippet above, but I do get this warning when using `instructor.from_openai(...)`. Specifically, there are three places that processing an OpenAI response (using `Mode.TOOLS`) seems to access `Mode.FUNCTIONS`, which triggers the warning due to the patched metaclass on Mode. (instructor v1.3.4).

Repro (v1.3.4, python 3.10):
```py
>>> import instructor
>>> import openai
>>> import warnings
>>> warnings.simplefilter("default")
>>> client = instructor.from_openai(openai.OpenAI())
.../python3.10/site-packages/instructor/client.py:396: DeprecationWarning: FUNCTIONS is deprecated and will be removed in future versions
  instructor.Mode.FUNCTIONS,
```

Warnings triggered by a full request/response flow:
```
site-packages/instructor/client.py:396: DeprecationWarning: FUNCTIONS is deprecated and will be removed in future versions
    instructor.Mode.FUNCTIONS,

site-packages/instructor/process_response.py:236: DeprecationWarning: FUNCTIONS is deprecated and will be removed in future versions
    if mode == Mode.FUNCTIONS:

site-packages/instructor/function_calls.py:121: DeprecationWarning: FUNCTIONS is deprecated and will be removed in future versions
    if mode == Mode.FUNCTIONS:
```

**Comment by faroukcharkas** [comment]
Any word on this?

**Comment by intellectronica** [comment]
Looks like  `__getattribute__('FUNCTIONS')` is called in some cases even though the consumer isn't trying to access the attribute. Maybe this is not an ideal place to implement the deprecation warning. Not a big deal, just a warning, but it pollutes the logs.

**Comment by faroukcharkas** [comment]
Yeah I agree--

My situation is strange, on normal usage it doesn't trigger it, but whenever I try and run it in Pytest it does.
