### ISSUE TITLE
ModuleNotFoundError: No module named 'google'

### ISSUE THREAD

**Issue by dbmikus** [jxnl/instructor#697]
- [x] This is actually a bug report.

**Describe the bug**

On Instructor version 1.3.0, the `__init__.py` file tries to use the `importlib.util.find_spec("google.generativeai")`. `google-generativeai` is an optional dependency, so I do not have the `google` parent package installed.

[Git blame link](https://github.com/jxnl/instructor/blame/92d0271af27c9107954c78005e16f10c4a1d2161/instructor/__init__.py#L55)

**To Reproduce**

Install the latest version to a new virtualenv, then in a Python repl:

```
import instructor

# results in:
# > ModuleNotFoundError: No module named 'google'
```

You can verify the problem:

```
import importlib

assert importlib.util.find_spec('google') is None

found_err = False
try:
    importlib.util.find_spec('google.generativeai')
except ModuleNotFoundError:
    found_err = True
assert found_err
```

**Expected behavior**

We should not need any optional dependencies installed to use the package.

**Comment by jxnl** [comment]
oh shit, are you able to make a PR I'm in a meeting rn

**Comment by dbmikus** [comment]
Sure, let me put one together.

**Comment by dbmikus** [comment]
PR is up. Review and/or merge at your convenience.
