### ISSUE TITLE
Compatibility with Langchain

### ISSUE THREAD

**Issue by andrewmartin592** [jxnl/instructor#70]
**Is your feature request related to a problem? Please describe.**
Would like to resolve dependency incompatibility between `langchain` and `openai_function_call`

**Describe the solution you'd like**
`langchain` and `openai_function_call` to be compatiable

**Describe alternatives you've considered**
None

**Additional context**
```
  Because no versions of openai-function-call match >0.2.0,<0.3.0
   and openai-function-call (0.2.0) depends on pydantic (>=2.0.2,<3.0.0), openai-function-call (>=0.2.0,<0.3.0) requires pydantic (>=2.0.2,<3.0.0).
  And because langchain (0.0.238) depends on pydantic (>=1,<2)
   and no versions of langchain match >0.0.238,<0.0.239, openai-function-call (>=0.2.0,<0.3.0) is incompatible with langchain (>=0.0.238,<0.0.239).
  So, because nira-ai depends on both langchain (^0.0.238) and openai-function-call (^0.2.0), version solving failed.
```

**Comment by jxnl** [comment]
Langchain uses their own pydantic parsing extraction.  Is there a feature you want from this library that isn’t supported by langchain ?

**Comment by sunilkgrao** [comment]
+1

are you saying langchain can already do what this library does @jxnl ?

**Comment by sunilkgrao** [comment]
freezing openai-function-call==0.2.1 solved this for me @andrewmartin592

**Comment by andrewmartin592** [comment]
> Langchain uses their own pydantic parsing extraction. Is there a feature you want from this library that isn’t supported by langchain ?

I'd love to build something like langchain's `create_pandas_dataframe_agent`. If you could give me a nudge in the right direction on how to do that with this library, that would be amazing

**Comment by andrewmartin592** [comment]
> freezing openai-function-call==0.2.1 solved this for me @andrewmartin592

```  Because no versions of langchain match >0.0.240,<0.0.241
   and langchain (0.0.240) depends on pydantic (>=1,<2), langchain (>=0.0.240,<0.0.241) requires pydantic (>=1,<2).
  And because openai-function-call (0.2.1) depends on pydantic (>=2.0.2,<3.0.0), langchain (>=0.0.240,<0.0.241) is incompatible with openai-function-call (0.2.1).
  So, because pipeline depends on both openai-function-call (0.2.1) and langchain (^0.0.240), version solving failed.```

**Comment by jxnl** [comment]
otherwise i would literally just copy paste https://github.com/jxnl/openai_function_call/blob/5d7b1a4ee05ab4759a17c79c6a1727c1f1ce3dae/openai_function_call/function_calls.py into your code.

**Comment by nnWhisperer** [comment]
Langchain doesn't seem to have the data validation of instructor library (like your great example here: https://python.useinstructor.com/blog/2023/11/18/validate-citations/). So, I'd like to use instructor with langchain. How can we do it? Thanks for the great library btw. @jxnl Jason.
