### ISSUE TITLE
create & create_with_completion fails on non-BaseModel classes

### ISSUE THREAD

**Issue by Chasearmer** [jxnl/instructor#709]
- [X] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [X] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [X] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**
chat.client.create_with_completion & chat.client.create fails on non-BaseModel classes, such as Enum.

**To Reproduce**
Version:
>Name: instructor
Version: 1.3.2
Summary: structured outputs for llm
Home-page: https://github.com/jxnl/instructor
Author: Jason Liu
Author-email: jason@jxnl.co
License: MIT
Location: /Users/.../lib/python3.12/site-packages
Requires: aiohttp, docstring-parser, openai, pydantic, pydantic-core, rich, tenacity, typer

Code:
```
class RiskOfBiasLevel(Enum):
    LOW_RISK = "low risk"
    PARTIAL_RISK = "partial risk"
    HIGH_RISK = "high risk"

class RiskOfBiasModel(BaseModel):
    risk_level: int

for response_model in [RiskofBiasModel, RiskOfBiasLevel]: 
  client = instructor.from_openai(OpenAI())
  response, completion = client.chat.completions.create_with_completion(
      model=GPT_4_TURBO,
      response_model=response_model,
      messages=[{"role": "user", "content": " "}],
      max_retries=3,
  )
```

Returns error:

>   File "/Users/.../myfile.py", line 393, in myFunction
    response, completion = client.chat.completions.create_with_completion(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../python3.12/site-packages/instructor/client.py", line 239, in create_with_completion
    return model, model._raw_response
                  ^^^^^^^^^^^^^^^^^^^
AttributeError: 'RiskOfBiasLevel' object has no attribute '_raw_response'

This error appears with client.chat.completions.create as well. It also failes on primitive types such as `int`

**Expected behavior**
The create and create_with_completion should work with non-BaseModel response models

**Comment by Chasearmer** [comment]
This [Concepts page](https://python.useinstructor.com/concepts/types/#what-happens-behind-the-scenes) claims that Enum is supported, in addition to Primitive Types (str, int, float, bool)

**Comment by ivanleomk** [comment]
@Chasearmer the concepts page example is using the `create` endpoint and not the `create_with_completion` function which returns the model and the raw_response instead of just the model. In the case of simple primitives, it will throw an error since the `_raw_response` property doesn't exist.

if you'd like to use a enum then you'll need to use the `create` endpoint. If not then the example should work nicely if you just use a wrapper BaseModel class around the enum.

**Comment by heyitsaamir** [comment]
I would like to reopen this. I'm getting the same problem with `create_model` where I dynamically build my model during runtime. 

```python
class SendMessageToPerson(BaseModel):
    """
    Allows the PA to send a message to a person in the conversation
    """

    reason: str = Field(..., description="Reason about the PA's response")
    response: str = Field(..., description="The PA's response to the user's inquiry")
    recipient_participant: str = Field(..., description="Name of the person that you want to send this message to")

...

allowed_recipients = Union[Literal[user1.name], Literal[user2.name]]
SendMessageToApplicableUsers = create_model(
            "SendMessageToPerson",
            recipient_participant=(
                allowed_recipients,
                Field(..., description="Name of the person that you want to send this message to"),
            ),
            __base__=SendMessageToPerson,
        )
```

cc: @jxnl / @ivanleomk

**Comment by benwhalley** [comment]
It would also be more convenient to have create_with_completion default to returning a string as the completion in the case that a `response_model` is not passed.
