### ISSUE TITLE
'List' response models raise exception when using create_with_completion

### ISSUE THREAD

**Issue by marcelrassinger** [jxnl/instructor#712]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [x] Other (please specify): claude-3-opus-20240229

**Describe the bug**

If you execute the code below you get 
`AttributeError: 'list' object has no attribute '_raw_response'`

But if you use create instead of create_with_completion, everything works fine.

**To Reproduce**

Execute the code:
```python
class User(BaseModel):
    name: str
    age: int

client = instructor.from_anthropic(Anthropic(api_key=anthropic_api_key))

# note that client.chat.completions.create will also work
resp, completion = client.messages.create_with_completion(
    model="claude-3-opus-20240229",
    max_tokens=1024,
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old. And Bruno 10 years.",
        }
    ],
    response_model=List[User],
)
```

**Expected behavior**

For the expected result just switch from. create_with_completion to create.

**Screenshots**

**Comment by jxnl** [comment]
ah this is known issue, 

please use 

Class Users:
   users: List[User] 
   
   for now

**Comment by marcelrassinger** [comment]
Ok, thanks for the very quick answer!

From: Jason Liu ***@***.***>
Date: Wednesday, 29 May 2024 at 16:05
To: jxnl/instructor ***@***.***>
Cc: marcelrassinger ***@***.***>, Author ***@***.***>
Subject: Re: [jxnl/instructor] 'List' response models raise exception when using create_with_completion (Issue #712)

ah this is known issue,

please use

Class Users:
users: List[User]

for now
