### ISSUE TITLE
Request: Add Support for VertexAI Gemini Models in Litellm with Instructor.

### ISSUE THREAD

**Issue by punjabdhaputar** [jxnl/instructor#748]
**Is your feature request related to a problem? Please describe.**
I would like to use Instructor with Litellm and Gemini 1.5.

Currently when I try to use litellm + instructor + gemini 1.5 I get the following error:
```
APIError: VertexAIException - Unknown field for Schema: $defs 
Model: gemini-1.5-pro-preview-0514
````
**Describe the solution you'd like**
I would like Gemini models to work similarly to Claude and OpenAI models in litellm + Instructor.

**Comment by ajac-zero** [comment]
I [mentioned ](https://github.com/jxnl/instructor/pull/711#issuecomment-2161647292) the cause of this issue in #711
