### ISSUE TITLE
Overload for `response_model=None` for `create(...)`

### ISSUE THREAD

**Issue by nathan-gage** [jxnl/instructor#749]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [x] I have tried searching the documentation and have not found an answer.

**What Model are you using?**
n/a

**Describe the bug**
Older versions of instructor supported `response_model=None`, now the type hinting disallows it.

**To Reproduce**
```python
client = instructor.from_openai(OpenAI())
client.create(model="gpt-3.5-turbo", response_model=None, messages=[{"role": "user", "content": "Hello!"}])

# Argument "response_model" to "create" of "Instructor" has incompatible type "None"; expected "type[Never]"
# mypy[arg-type](https://mypy.readthedocs.io/en/stable/_refs.html#code-arg-type)
```

**Expected behavior**
I should be able to get regular ChatCompletions -- I'm not sure how this would behave if using a non-OpenAI client, I assume the `OpenAISchema` class handles that (is it just confusingly named?)

---
https://github.com/jxnl/instructor/blob/8a3f365bf3676edd32790bf469f1ebf51c8c1646/instructor/client.py#L79-L88

I would love to submit a PR for this but am limited on time, although it may be as simple as adding a single `@overload`. I maybe get to it on the weekend.

**Comment by ivanleomk** [comment]
@nathan-gage could you try updating to the latest version of instructor? I tried running the code sample provided above and didn't manage to reproduce the error.

```python
import instructor
from openai import OpenAI

client = instructor.from_openai(OpenAI())
print(
    client.chat.completions.create(
        model="gpt-3.5-turbo",
        response_model=None,
        messages=[{"role": "user", "content": "Hello!"}],
    )
)
print(
    client.create(
        model="gpt-3.5-turbo",
        response_model=None,
        messages=[{"role": "user", "content": "Hello!"}],
    )
)
```

This created the response of 

```bash
ChatCompletion(id='chatcmpl-9Za5QJirClLTxCOkWsVCOun1QakF6', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! How can I assist you today?', role='assistant', function_call=None, tool_calls=None))], created=1718267224, model='gpt-3.5-turbo-0125', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=9, prompt_tokens=9, total_tokens=18))
ChatCompletion(id='chatcmpl-9Za5Rj3OHFTUhoVQ0cGgaYaIgtOYc', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Hello! How can I assist you today?', role='assistant', function_call=None, tool_calls=None))], created=1718267225, model='gpt-3.5-turbo-0125', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=9, prompt_tokens=9, total_tokens=18))
```

**Comment by nathan-gage** [comment]
@ivanleomk this was on version 1.3.3. I get the same output, the issue is with the type hints and not the code itself. The problem would be typing the downstream code to hint properly given the underlying client.

**Comment by ivanleomk** [comment]
Ah ok, gotcha on that. I'll take a closer look at it over the weekend when I get the time then. Happy to work together on a PR if you've got some ideas.
