### ISSUE TITLE
Unable to import instructor due to client_vertexai.py

### ISSUE THREAD

**Issue by raineydavid** [jxnl/instructor#772]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**
Fails over on import instructor due to import jsonref in client_vertexai.py.  Trying to use gpt-4o however hadn't even got to specificying the model.

**To Reproduce**
install instructor 
import instructor

**Expected behavior**
Works

**Screenshots**
![image](https://github.com/jxnl/instructor/assets/23113728/2090a43b-f674-40cf-8084-9d9e70531141)

**Comment by lemontheme** [comment]
Quick fix in the meantime is to `pip install instructor[vertexai]` or just `pip install jsonref`, or `pip uninstall google-cloud-aiplatform` in case you're not using it.

**Comment by ivanleomk** [comment]
Hey @raineydavid , the easiest way for this is just to use the installation command listed here for your specific client. 

Link : https://python.useinstructor.com/#getting-started

We only ship with the openai client by default.
