### ISSUE TITLE
Invalid Discord link

### ISSUE THREAD

**Issue by wasauce** [jxnl/instructor#777]
![Screenshot 2024-06-21 at 9 38 11 PM](https://github.com/jxnl/instructor/assets/41729/00665a29-31c5-44ee-b994-d2a88b35fdbd)

When you go to https://python.useinstructor.com/ and try to join the discord the above is what you get.

**Comment by ivanleomk** [comment]
Hey @wasauce , I don't seem to get the same error. But I regenerated a new link for you to the discord here - https://discord.gg/Z5F4g8TA, can you see if it works for you?

**Comment by wasauce** [comment]
@ivanleomk thank you! Yes this worked.
