### ISSUE TITLE
Issue with 1.3.6 on Cohere not installed.

### ISSUE THREAD

**Issue by fer-git** [jxnl/instructor#875]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [x] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**
The issue lies on importing `cohere` python client, while `cohere` is not installed in the environment.

```sh
  File ".venv/lib/python3.10/site-packages/instructor/function_calls.py", line 16, in <module>
    from cohere import NonStreamedChatResponse
ModuleNotFoundError: No module named 'cohere'
```

**Comment by ivanleomk** [comment]
@fer-git thanks for pointing this out. I have a PR that addresses this soon, just need to do a bit more testing to make sure cohere works nicely before we can fix this.

Sorry about the trouble causes

**Comment by avyfain** [comment]
Oh, I knee-jerk opened https://github.com/jxnl/instructor/pull/876

**Comment by nheingit** [comment]
For anyone else hitting this I downgraded to 1.3.4 and that fixed my problem.

**Comment by jxnl** [comment]
redeploying now
