### ISSUE TITLE
Optional[List] as field type crashes with streaming

### ISSUE THREAD

**Issue by ahuang11** [jxnl/instructor#880]
- [x] This is actually a bug report.
- [ ] I am not getting good LLM Results
- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer.

**What Model are you using?**

- [x] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)

**Describe the bug**

In `openai_schema_helper`, `issubclass(cls)` crashes when `list[str] | None`

**To Reproduce**
Steps to reproduce the behavior, including code snippets of the model and the input data and openai response.

```python
import instructor
from typing import Optional
from instructor import Partial
from pydantic import BaseModel
from openai import AsyncOpenAI



# Define your desired output structure
class UserInfo(BaseModel):
    name: Optional[list[str]]
    age: int


# Patch the OpenAI client
client = instructor.from_openai(AsyncOpenAI())

# Extract structured data from natural language
user_info = await client.chat.completions.create(
    model="gpt-3.5-turbo",
    response_model=Partial[UserInfo],
    messages=[{"role": "user", "content": "John Doe is 30 years old."}],
    stream=True
)

async for chunk in user_info:
    print(chunk)
```

**Expected behavior**

Works like without streaming.

**Screenshots**

**Comment by michael-quinlan** [comment]
I think this is the same as https://github.com/jxnl/instructor/issues/878 but this issue has a nice small reproduction step.

**Comment by ahuang11** [comment]
Thanks for letting me know. I'll close this as duplicate.

**Comment by michael-quinlan** [comment]
I think it's fine to also leave it open, this is my first PR in this repo, so I don't know the protocols they follow. I'm just trying to help get a fix out as more people will hit this now it's in the 'latest version'

Btw I'm more than happy for the real fix not being my PR, that's just my attempt, so others who have better solutions should go ahead.
