### ISSUE TITLE
Return types with response_model are less clear now

### ISSUE THREAD

**Issue by noxan** [jxnl/instructor#881]
The update from #860 is great, but it made the return types less clear. Now, instead of specific types, we get `T | Any`, which doesn't tell us an exact type and makes working with types downstream much more complicated.

Working towards a solution: We could override the method definition for the case of `response_model` being defined or `None`. Downside is we double the number of function overloads.

Here a short snippet from our internal wrapper for illustration:
```python
@overload
def completion(
    model: ModelType,
    messages: list,
    response_model: None = ...,
    max_retries: int = ...,
) -> Any: ...


@overload
def completion[T_Model: BaseModel](
    model: ModelType,
    messages: list,
    response_model: Type[T_Model],
    max_retries: int = ...,
) -> T_Model: ...


def completion[T_Model: BaseModel](
    model: ModelType,
    messages: list,
    response_model: Type[T_Model] | None = None,
    max_retries: int = 1,
) -> T_Model | Any:
```

Would be glad to hear your thoughts and then happy to support working on a pull request.

**Comment by jxnl** [comment]
we should do that, thats an oversight on my side @ssonal

**Comment by jxnl** [comment]
would love a PR

**Comment by ssonal** [comment]
Sorry I wasn't able to figure this one out. 

I did find that type checking is off for async clients though - was that the issue @noxan? Looks ok for standard clients / simple types / BaseModels.

**Comment by noxan** [comment]
@ssonal Thanks for investigating. I believe the problem lies in how we wrapped instructor while the typing still were more fuzzy.

Here an example: https://github.com/noxan/instructor-typing-sample/blob/main/main.py#L27

I can confirm instructor works great with the first two sample calls, however the return types are all over the place with the wrapper function. Originally we had custom generic types does not make a difference to importing `T` from instructor. Regardless this is most likely me messing up generic types or a limitation of pyright to infer the exact return type.

<img width="684" alt="Screenshot 2024-07-29 at 11 22 04 AM" src="https://github.com/user-attachments/assets/8559eb50-bbbb-4804-a050-fdffad2730e8">

Let me know if you have any thoughts, else I believe we can close this again, as it seems not directly related to instructor.

**Comment by jxnl** [comment]
I think we should increase the overloads. Unfortunately, there is a side effect of Python's system.

@ivanleomk next time you make changes can you make sure we don't break the types

**Comment by jxnl** [comment]
I would almost rather tell people if you want to use instructor with response=None just use a different client

**Comment by noxan** [comment]
@jxnl added a few more examples and continued the investigation. the new type annotations do not work with pyright and actually made things worse. here an example project https://github.com/noxan/instructor-typing-sample/actions/runs/10409008348/job/28827657705 

might also be related to https://github.com/jxnl/instructor/issues/893
