### ISSUE TITLE
Request: Pydantic types from openapi.json to make restful agent

### ISSUE THREAD

**Issue by jxnl** [jxnl/instructor#9]
there should be some tools that can get pydantic from openapi.json

would love to see an example like 

```
endpoints = Endpoints.from("www.website.com/openapi.json")

completion = openai.ChatCompletion(
   function_call=endpoints
   ...
   )
```

**Comment by atemaguer** [comment]
does [this](https://github.com/koxudaxi/datamodel-code-generator) seem like a good tool for parsing an openapi.json spec into pydantic models? it seems it's stable enough to be used in projects and netflix and aws.

**Comment by jxnl** [comment]
Oh wow I don’t have much time this week, but would you be interested in contributing something to the Docs?

**Comment by atemaguer** [comment]
Yeah sure. Direct me to an issue or create one
