### ISSUE TITLE
Support OpenAI API's new guaranteed structured output

### ISSUE THREAD

**Issue by ChristianWeyer** [jxnl/instructor#910]
This:
https://openai.com/index/introducing-structured-outputs-in-the-api/

😁

**Comment by mrmuke** [comment]
YES PLEASE

**Comment by AlmogBaku** [comment]
that was fast

**Comment by richardyc** [comment]
+1!

**Comment by ogunoz** [comment]
+1

**Comment by dogonthehorizon** [comment]
It looks like the associated PR is here:
https://github.com/jxnl/instructor/pull/916

@mrmuke @richardyc @ogunoz in the future, [adding a reaction to the OPs issue](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) achieves the same goal of expressing interest in an issue while keeping everyone's notifications tidy :)

**Comment by ivanleomk** [comment]
Closing this issue for now! Yes we support structured outputs using the `TOOLS_STRICT` mode at the moment that uses strict function calling.
