### ISSUE TITLE
 AttributeError: module 'instructor' has no attribute 'from_openai'

### ISSUE THREAD

**Issue by JohnTan38** [jxnl/instructor#918]
- [ ] This is actually a bug report.

- [ ] I have tried asking for help in the community on discord or discussions and have not received a response.
- [ ] I have tried searching the documentation and have not found an answer. Which version of instructor has from_openai method?
- [ ] 

**What Model are you using?**

- [ ] gpt-3.5-turbo
- [ ] gpt-4-turbo
- [ ] gpt-4
- [ ] Other (please specify)  model="gpt-4-vision-preview",

**Describe the bug**
Execute code from this notebook:
https://github.com/jxnl/instructor/blob/main/examples/vision/run_table.py
AttributeError: module 'instructor' has no attribute 'from_openai'

**To Reproduce**
Steps to reproduce the behavior, including code snippets of the model and the input data and openai response.

**Expected behavior**

**Screenshots**

**Comment by ivanleomk** [comment]
@JohnTan38 what version of instructor are you using? `from_openai` was introduced in v1.x onwards so if you're using a version thats 0.x then that might be causing this

**Comment by JohnTan38** [comment]
Hi sir. Yes I've re installed the correct versions and libraries. Code is running well. Thank you for this great application :)
