### ISSUE TITLE
Instructor with Lagchain bind_tools?

### ISSUE THREAD

**Issue by aleibovici** [jxnl/instructor#920]
I am using Langchain with bind_tools for OpenAI.
Is it possible to use Instructor with Langchain? How?

`functions = [
            {
                "name": "identify_columns",
                "description": "Identify column types in a dataset",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "item1": {"type": "string", "description": "description"},
                                    "item2": {"type": "string", "description": "description"},
                                    "item3": {"type": "number", "description": "description"},
                                    "item4": {"type": "number", "description": "description"}
                                }
                            }
                        }
                    },
                    "required": ["data_sample"]
                }
            }
        ]`

`# Bind the functions to the model
        llm_with_tools = llm.bind_tools(functions)
`

**Comment by jxnl** [comment]
nope you should just use their structured output tools
