### ISSUE TITLE
Integrate BAML support into Instructor for enhanced LLM function handling and structured output

### ISSUE THREAD

**Issue by phatlast96** [jxnl/instructor#926]
**Is your feature request related to a problem? Please describe.**
Currently, Instructor.py lacks native support for BAML (Boundary Markup Language), a domain-specific language for writing and testing LLM functions. This means users who want to leverage both Instructor's structured output capabilities and BAML's powerful LLM function definitions have to use workarounds or manage two separate systems, which can be inefficient and error-prone.

**Describe the solution you'd like**
Integrate BAML support directly into Instructor.py. This integration could include:
1. The ability to define Instructor models using BAML syntax
2. A way to import BAML function definitions into Instructor
3. Automatic conversion of BAML output types to Pydantic models
4. Support for BAML's input variable definitions within Instructor's API
5. Compatibility with BAML's testing and validation features

**Describe alternatives you've considered**
1. Creating a separate wrapper library that connects Instructor and BAML
2. Using Instructor's existing customization options to manually implement BAML-like functionality
3. Encouraging users to use BAML and Instructor side-by-side without direct integration

**Additional context**
This integration would combine the strengths of both tools: Instructor's ease of use for structured outputs and Pydantic integration, and BAML's powerful LLM function definitions and superior performance in getting structured data. It would provide a more streamlined workflow for developers working with LLMs, allowing them to leverage the best of both worlds in a single, cohesive system.

https://github.com/BoundaryML/baml

**Comment by jxnl** [comment]
out of scope, any integration should be done on their side.
