### ISSUE TITLE
JsonDecoderError at the specific place

### ISSUE THREAD

**Issue by yitianlian** [jxnl/instructor#94]
**Describe the bug**
When Using the instructor, at some input. It will raise json error fault.

**To Reproduce**

**Expected behavior**
A way to fix the bug

**Screenshots**
![image](https://github.com/jxnl/instructor/assets/91449279/07597bb4-cf4c-451f-99f9-5f0d8fdf91db)

**Desktop (please complete the following information):**
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

**Comment by jxnl** [comment]
can you send a gist of a example api call + schema?

**Comment by yitianlian** [comment]
I find the solution  in [https://github.com/jxnl/instructor/issues/32](url)
