### ISSUE TITLE
Bump to jiter<1

### ISSUE THREAD

**Issue by Elektra58** [jxnl/instructor#960]
**Is your feature request related to a problem? Please describe.**
instructor can not be installed together with aider-chat due to a version conflict of the jiter package. The [ai-scientist](https://github.com/SakanaAI/AI-Scientist) depends on aider-chat
**Describe the solution you'd like**
Bump instructor to use the same version dependency for jiter as openai, anthropic, litellm, etc.

**Additional context**
Here is the reverse dependency tree for some of the major llms as compared to instructor:
jiter==0.4.2
├── anthropic==0.30.1 [requires: jiter>=0.4.0,<1]
├── instructor==1.4.0 [requires: jiter>=0.4.1,<0.5.0]
└── openai==1.42.0 [requires: jiter>=0.4.0,<1]

aider-chat requires
aider-chat==0.52.1
├── jiter [required: ==0.5.0, installed: 0.5.0]

**Comment by ivanleomk** [comment]
We've merged this and it's been published with the latest version of instructor. Do let me know if it doesn't work @Elektra58 . Going to close this for now
