### ISSUE TITLE
o1-preview support (max_tokens -> max_completion_tokens)

### ISSUE THREAD

**Issue by alexmoini** [jxnl/instructor#990]
**Is your feature request related to a problem? Please describe.**
o1-preview model doesn't support most params / has new name for max_tokens. Notably max_tokens -> max_completion_tokens.

I believe by just removing the max_tokens / switching it to max_completion_tokens when model = 'o1-preview' will fix as long as MD_JSON mode is used.

**Describe the solution you'd like**
Support for o1-preview for instructor.from_openai(...)

**Describe alternatives you've considered**
LiteLLM + instructor (litellm doesn't support yet); middle-ware api + change openAI url

**Comment by ivanleomk** [comment]
Hey @alexmoini I just pushed up a new PR here : https://github.com/jxnl/instructor/pull/991, once it's merged in this should work. 

> I believe by just removing the max_tokens / switching it to max_completion_tokens when model = 'o1-preview' will fix as long as MD_JSON mode is used.

O1 doesn't support a system parameter too for now during the beta phase

<img width="970" alt="CleanShot 2024-09-13 at 11 57 18@2x" src="https://github.com/user-attachments/assets/f587a23b-4adb-4b92-ad74-1052ba3ec20a">

**Comment by alexmoini** [comment]
Yup, thanks Ivan.
